const questionBank = {
  math: [
    { id: 1, topic: "Set Theory", question: "If set A = {1, 3, 5, 7, 9} and set B = {2, 3, 5, 7}, what is A ∩ B?", options: ["{1, 2, 9}", "{3, 5, 7}", "{1, 2, 3, 5, 7, 9}", "Ø"], answer: 1 },
    { id: 2, topic: "Indices", question: "Evaluate (81)^(-3/4)", options: ["27", "1/27", "9", "1/9"], answer: 1 },
    { id: 3, topic: "Logarithms", question: "Solve for x in the equation: 3^(2x) = 27", options: ["1", "1.5", "3", "4.5"], answer: 1 },
    { id: 4, topic: "Simple Interest", question: "Find the simple interest on ₦40,000 for 3 years at 5% per annum.", options: ["₦5,000", "₦6,000", "₦4,000", "₦8,000"], answer: 1 },
    { id: 5, topic: "Number Bases", question: "Convert 1101 base 2 to base 10.", options: ["13", "11", "15", "12"], answer: 0 },
    { id: 6, topic: "Variation", question: "If y varies inversely as x, and y=4 when x=3, find y when x=6.", options: ["2", "4", "6", "12"], answer: 0 },
    { id: 7, topic: "Algebra", question: "Factorize completely: 2x² - 8", options: ["2(x-2)(x+2)", "2(x-4)(x+1)", "(2x-4)(x+2)", "2(x-2)²"], answer: 0 },
    { id: 8, topic: "Coordinate Geometry", question: "The gradient of the line passing through points P(2, 5) and Q(4, 9) is:", options: ["4", "3", "2", "1"], answer: 2 },
    { id: 9, topic: "Trigonometry", question: "If tan θ = 3/4, find the value of sin θ (where θ is acute).", options: ["3/5", "4/5", "3/7", "5/3"], answer: 0 },
    { id: 10, topic: "Statistics", question: "Find the mean of the numbers: 2, 4, 6, 8, 10.", options: ["4", "5", "6", "8"], answer: 2 },
    { id: 11, topic: "Logarithms", question: "Evaluate log10(0.0001)", options: ["-3", "-4", "4", "3"], answer: 1 },
    { id: 12, topic: "Geometry", question: "Sum of interior angles of a pentagon is?", options: ["360°", "540°", "720°", "180°"], answer: 1 },
    { id: 13, topic: "Probability", question: "Probability of picking a red ball from 3 red and 5 blue balls?", options: ["3/5", "5/8", "3/8", "1/2"], answer: 2 },
    { id: 14, topic: "Calculus", question: "Find the derivative of y = 3x²", options: ["3x", "6x", "x³", "6"], answer: 1 },
    { id: 15, topic: "Binary Operations", question: "If a * b = a + b + ab, find 2 * 3", options: ["5", "6", "11", "10"], answer: 2 },
    { id: 16, topic: "Inequalities", question: "Solve 2x + 3 < 11", options: ["x < 4", "x > 4", "x < 7", "x > 7"], answer: 0 },
    { id: 17, topic: "Surds", question: "Simplify √75", options: ["3√5", "5√3", "15√3", "25√3"], answer: 1 },
    { id: 18, topic: "Sequence/Series", question: "Find the 5th term of the AP: 2, 5, 8...", options: ["11", "14", "17", "13"], answer: 1 },
    { id: 19, topic: "Polygons", question: "Each exterior angle of a regular octagon is?", options: ["45°", "60°", "30°", "90°"], answer: 0 },
    { id: 20, topic: "Matrices", question: "The determinant of [[2,3],[1,4]] is?", options: ["5", "11", "8", "3"], answer: 0 }
  ],
  english: [
    { id: 21, topic: "Synonyms", question: "Nearest in meaning: The man was 'vindicated'.", options: ["Condemned", "Accused", "Freed from blame", "Imprisoned"], answer: 2 },
    { id: 22, topic: "Antonyms", question: "Opposite in meaning: The driver was 'reckless'.", options: ["Careless", "Cautious", "Fast", "Drunk"], answer: 1 },
    { id: 23, topic: "Spelling", question: "Which is correctly spelt?", options: ["Embarassment", "Embarrassment", "Embarrasment", "Embarrassmant"], answer: 1 },
    { id: 24, topic: "Verbs", question: "The boy ______ the book on the table yesterday.", options: ["lay", "laid", "lied", "lain"], answer: 1 },
    { id: 25, topic: "Vocabulary", question: "Nearest in meaning: It was a 'futile' attempt.", options: ["Successful", "Dangerous", "Useless", "Clever"], answer: 2 },
    { id: 26, topic: "Phonology", question: "Which word rhymes with 'Hair'?", options: ["Here", "Hear", "Air", "Her"], answer: 2 },
    { id: 27, topic: "Concord", question: "Neither of the boys ______ present at the party.", options: ["were", "was", "are", "have been"], answer: 1 },
    { id: 28, topic: "Idioms", question: "'He has a finger in every pie.' This means he...", options: ["Loves eating", "Is a baker", "Is involved in many things", "Injured"], answer: 2 },
    { id: 29, topic: "Antonyms", question: "Opposite in meaning: 'Hostile'.", options: ["Friendly", "Aggressive", "Warm", "Harsh"], answer: 0 },
    { id: 30, topic: "Conditionals", question: "If I ______ you, I would accept the offer.", options: ["am", "was", "were", "be"], answer: 2 },
    { id: 31, topic: "Tenses", question: "She ______ since morning.", options: ["slept", "is sleeping", "has been sleeping", "was sleeping"], answer: 2 },
    { id: 32, topic: "Prepositions", question: "He is proficient ______ English.", options: ["at", "in", "with", "by"], answer: 1 },
    { id: 33, topic: "Question Tags", question: "You are coming, ______?", options: ["is it", "aren't you", "don't you", "not so"], answer: 1 },
    { id: 34, topic: "Spelling", question: "Which is correctly spelt?", options: ["Manoeuvre", "Manouvre", "Maneuvre", "Manuever"], answer: 0 },
    { id: 35, topic: "Adjectives", question: "That is a ______ car.", options: ["blue fast Japanese", "fast Japanese blue", "fast blue Japanese", "Japanese fast blue"], answer: 2 },
    { id: 36, topic: "Idioms", question: "'Kick the bucket' means?", options: ["To play", "To die", "To be angry", "To work"], answer: 1 },
    { id: 37, topic: "Pronouns", question: "It is ______ who spoke.", options: ["me", "I", "him", "them"], answer: 1 },
    { id: 38, topic: "Synonyms", question: "Nearest in meaning: 'Incessant'.", options: ["Stop", "Constant", "Intermittent", "Rare"], answer: 1 },
    { id: 39, topic: "Antonyms", question: "Opposite in meaning: 'Fragile'.", options: ["Weak", "Strong", "Breakable", "New"], answer: 1 },
    { id: 40, topic: "Grammar", question: "One of the ______ arrived.", options: ["man", "men", "mans", "mens"], answer: 1 }
  ],
  physics: [
    { id: 41, topic: "Units", question: "Which of the following is a derived unit?", options: ["Ampere", "Kilogram", "Newton", "Kelvin"], answer: 2 },
    { id: 42, topic: "Dynamics", question: "The rate of change of momentum is proportional to?", options: ["Velocity", "Acceleration", "Force", "Inertia"], answer: 2 },
    { id: 43, topic: "Heat Transfer", question: "Heat from the sun reaches earth through?", options: ["Conduction", "Convection", "Radiation", "Evaporation"], answer: 2 },
    { id: 44, topic: "Optics", question: "Which mirror is used by dentists?", options: ["Plane", "Concave", "Convex", "Cylindrical"], answer: 1 },
    { id: 45, topic: "Electricity", question: "Instrument used to measure current is?", options: ["Voltmeter", "Ammeter", "Galvanometer", "Ohmmeter"], answer: 1 },
    { id: 46, topic: "Waves", question: "Sound waves are typically?", options: ["Transverse", "Longitudinal", "Electromagnetic", "Static"], answer: 1 },
    { id: 47, topic: "Thermal Physics", question: "Density of water is highest at?", options: ["0°C", "100°C", "4°C", "10°C"], answer: 2 },
    { id: 48, topic: "Newton's Laws", question: "Newton's first law deals with?", options: ["Inertia", "Force", "Action/Reaction", "Gravity"], answer: 0 },
    { id: 49, topic: "Energy", question: "The unit of Power is?", options: ["Joule", "Watt", "Pascal", "Newton"], answer: 1 },
    { id: 50, topic: "Modern Physics", question: "Alpha particles are?", options: ["Electrons", "Helium nuclei", "Protons", "Photons"], answer: 1 },
    { id: 51, topic: "Simple Machines", question: "Efficiency of a machine is?", options: ["MA/VR x 100", "VR/MA x 100", "Work in/Work out", "Always 100%"], answer: 0 },
    { id: 52, topic: "Elasticity", question: "Energy stored in a stretched spring?", options: ["Kinetic", "Elastic Potential", "Chemical", "Thermal"], answer: 1 },
    { id: 53, topic: "Fluid Pressure", question: "Pressure in a liquid depends on?", options: ["Area", "Depth", "Volume", "Shape"], answer: 1 },
    { id: 54, topic: "Refraction", question: "Bending of light through media is?", options: ["Reflection", "Refraction", "Diffraction", "Dispersion"], answer: 1 },
    { id: 55, topic: "Fields", question: "Region where magnetic influence is felt?", options: ["Electric field", "Magnetic field", "Gravitational field", "Flux"], answer: 1 },
    { id: 56, topic: "Gas Laws", question: "Process at constant temperature is?", options: ["Isobaric", "Isochoric", "Isothermal", "Adiabatic"], answer: 2 },
    { id: 57, topic: "Electronics", question: "The charge on an electron is?", options: ["Negative", "Positive", "Neutral", "Variable"], answer: 0 },
    { id: 58, topic: "Capacitance", question: "Unit of capacitance?", options: ["Farad", "Henry", "Tesla", "Weber"], answer: 0 },
    { id: 59, topic: "Kinematics", question: "Change in displacement over time?", options: ["Speed", "Acceleration", "Velocity", "Distance"], answer: 2 },
    { id: 60, topic: "Projectiles", question: "At max height, vertical velocity is?", options: ["Max", "Zero", "Initial", "Half"], answer: 1 }
  ],
  chemistry: [
    { id: 61, topic: "Atmosphere", question: "Most abundant gas in air?", options: ["O2", "N2", "CO2", "Ar"], answer: 1 },
    { id: 62, topic: "Acids/Bases", question: "PH of a neutral solution?", options: ["0", "7", "14", "1"], answer: 1 },
    { id: 63, topic: "Atomic Structure", question: "Atomic number represents?", options: ["Neutrons", "Electrons", "Protons", "Nucleons"], answer: 2 },
    { id: 64, topic: "Corrosion", question: "Iron rusting is an example of?", options: ["Hydration", "Oxidation", "Reduction", "Sublimation"], answer: 1 },
    { id: 65, topic: "Periodic Table", question: "Which is a noble gas?", options: ["Cl", "Ne", "H", "N"], answer: 1 },
    { id: 66, topic: "Hydrocarbons", question: "Alkanes have the formula?", options: ["CnH2n", "CnH2n+2", "CnH2n-2", "CnHn"], answer: 1 },
    { id: 67, topic: "Reaction Rates", question: "A substance that speeds up reaction?", options: ["Inhibitor", "Catalyst", "Solvent", "Solute"], answer: 1 },
    { id: 68, topic: "Water Chemistry", question: "Hard water contains ions of?", options: ["Na", "Ca and Mg", "K", "Ag"], answer: 1 },
    { id: 69, topic: "Chemical Bonding", question: "The bond in NaCl is?", options: ["Covalent", "Ionic", "Metallic", "Hydrogen"], answer: 1 },
    { id: 70, topic: "Organic Acids", question: "Acid found in citrus fruits?", options: ["Acetic", "Citric", "Tartaric", "HCl"], answer: 1 },
    { id: 71, topic: "Periodic Table", question: "Group 1 elements are?", options: ["Alkali metals", "Halogens", "Noble gases", "Transition"], answer: 0 },
    { id: 72, topic: "Separation Techniques", question: "Separating sand and water?", options: ["Distillation", "Filtration", "Chromatography", "Sublimation"], answer: 1 },
    { id: 73, topic: "Stoichiometry", question: "Avogadro's number is?", options: ["6.02x10^23", "3x10^8", "9.8", "1.6x10^-19"], answer: 0 },
    { id: 74, topic: "Energy Changes", question: "Reaction that absorbs heat?", options: ["Exothermic", "Endothermic", "Catalytic", "Spontaneous"], answer: 1 },
    { id: 75, topic: "Matter", question: "Gas to liquid transition is?", options: ["Evaporation", "Condensation", "Freezing", "Melting"], answer: 1 },
    { id: 76, topic: "Indicator", question: "Turning blue litmus red signifies?", options: ["Base", "Acid", "Salt", "Water"], answer: 1 },
    { id: 77, topic: "Metals", question: "Liquid metal at room temp?", options: ["Gold", "Mercury", "Silver", "Iron"], answer: 1 },
    { id: 78, topic: "Sub-atomic particles", question: "Negative charge particle?", options: ["Proton", "Neutron", "Electron", "Positron"], answer: 2 },
    { id: 79, topic: "Organic Chemistry", question: "Simplest organic compound?", options: ["Ethane", "Methane", "Propane", "Butane"], answer: 1 },
    { id: 80, topic: "Redox", question: "Loss of electrons is called?", options: ["Reduction", "Oxidation", "Neutralization", "Electrolysis"], answer: 1 }
  ],
  biology: [
    { id: 81, topic: "Cell Biology", question: "Powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondrion", "Vacuole"], answer: 2 },
    { id: 82, topic: "Homeostasis", question: "Maintaining constant internal environment?", options: ["Osmosis", "Homeostasis", "Diffusion", "Excretion"], answer: 1 },
    { id: 83, topic: "Genetics", question: "Universal donor blood group?", options: ["A", "B", "AB", "O"], answer: 3 },
    { id: 84, topic: "Digestion", question: "Enzyme in saliva?", options: ["Pepsin", "Ptyalin", "Renin", "Lipase"], answer: 1 },
    { id: 85, topic: "Organs", question: "Fish respiratory organ?", options: ["Lungs", "Gills", "Skin", "Trachea"], answer: 1 },
    { id: 86, topic: "Nutrition", question: "Vitamin from sunlight?", options: ["A", "B", "C", "D"], answer: 3 },
    { id: 87, topic: "Circulation", question: "Deoxygenated blood enters?", options: ["L. Atrium", "R. Atrium", "Aorta", "Pulmonary Vein"], answer: 1 },
    { id: 88, topic: "Cell Biology", question: "Control center of the cell?", options: ["Cytoplasm", "Nucleus", "Wall", "Membrane"], answer: 1 },
    { id: 89, topic: "Botany", question: "Insect pollination term?", options: ["Anemophily", "Entomophily", "Hydrophily", "None"], answer: 1 },
    { id: 90, topic: "Nervous System", question: "Brain part for balance?", options: ["Cerebrum", "Cerebellum", "Medulla", "Thalamus"], answer: 1 },
    { id: 91, topic: "Ecology", question: "Living part of ecosystem?", options: ["Biotic", "Abiotic", "Climate", "Soil"], answer: 0 },
    { id: 92, topic: "Nutrition", question: "Iodine tests for?", options: ["Starch", "Sugar", "Protein", "Fats"], answer: 0 },
    { id: 93, topic: "Excretion", question: "Mammalian waste organ?", options: ["Heart", "Liver", "Kidney", "Stomach"], answer: 2 },
    { id: 94, topic: "Taxonomy", question: "Father of classification?", options: ["Darwin", "Linnaeus", "Mendel", "Hooke"], answer: 1 },
    { id: 95, topic: "Genetics", question: "Father of genetics?", options: ["Linnaeus", "Mendel", "Watson", "Crick"], answer: 1 },
    { id: 96, topic: "Digestion", question: "Bile is stored in the?", options: ["Liver", "Gall bladder", "Pancreas", "Duodenum"], answer: 1 },
    { id: 97, topic: "Plants", question: "Xylem transports?", options: ["Food", "Water", "Hormones", "Oxygen"], answer: 1 },
    { id: 98, topic: "Endocrine", question: "Master gland is?", options: ["Thyroid", "Pituitary", "Adrenal", "Ovary"], answer: 1 },
    { id: 99, topic: "Evolution", question: "Survival of the fittest by?", options: ["Lamarck", "Darwin", "Mendel", "Aristotle"], answer: 1 },
    { id: 100, topic: "Microbiology", question: "Amoeba moves using?", options: ["Cilia", "Flagella", "Pseudopodia", "Tentacles"], answer: 2 }
  ],
  government: [
    { id: 101, topic: "Basic Concepts", question: "Ultimate power of state?", options: ["Authority", "Power", "Sovereignty", "Influence"], answer: 2 },
    { id: 102, topic: "Legislature", question: "Two house legislature?", options: ["Unicameral", "Bicameral", "Federal", "Unitary"], answer: 1 },
    { id: 103, topic: "Judiciary", question: "Highest court in Nigeria?", options: ["High", "Appeal", "Supreme", "Magistrate"], answer: 2 },
    { id: 104, topic: "Nationalism", question: "Father of Nigerian Nationalism?", options: ["Zik", "Macaulay", "Awolowo", "Bello"], answer: 1 },
    { id: 105, topic: "Franchise", question: "Suffrage means?", options: ["Work", "Vote", "Travel", "Speak"], answer: 1 },
    { id: 106, topic: "Constitutional History", question: "Nigeria's 1st Republic began?", options: ["1960", "1963", "1966", "1979"], answer: 1 },
    { id: 107, topic: "Constitutional History", question: "Basic law of a state?", options: ["Constitution", "Manifesto", "Decree", "Order"], answer: 0 },
    { id: 108, topic: "Executive", question: "Body that implements law?", options: ["Judiciary", "Legislature", "Executive", "Police"], answer: 2 },
    { id: 109, topic: "Democracy", question: "Government by the people?", options: ["Elite", "Democracy", "Kings", "Military"], answer: 1 },
    { id: 110, topic: "Federalism", question: "Capital moved to Abuja in?", options: ["1991", "1980", "1999", "2001"], answer: 0 },
    { id: 111, topic: "Citizenship", question: "Way to acquire citizenship?", options: ["Birth", "Theft", "Arrest", "Travel"], answer: 0 },
    { id: 112, topic: "Systems", question: "Powers shared between tiers?", options: ["Unitary", "Federal", "Confederal", "Monarchy"], answer: 1 },
    { id: 113, topic: "Parties", question: "Main aim of political party?", options: ["Socialize", "Win power", "Collect tax", "Travel"], answer: 1 },
    { id: 114, topic: "International Org", question: "UN headquarters location?", options: ["London", "Paris", "New York", "Geneva"], answer: 2 },
    { id: 115, topic: "Elections", question: "Body conducting Nigeria elections?", options: ["INEC", "EFCC", "NPC", "NUC"], answer: 0 },
    { id: 116, topic: "Public Service", question: "Civil service is?", options: ["Partisan", "Non-partisan", "Political", "Military"], answer: 1 },
    { id: 117, topic: "Local Govt", question: "Grassroots government?", options: ["State", "Federal", "Local", "Regional"], answer: 2 },
    { id: 118, topic: "History", question: "Lagos became Crown Colony?", options: ["1861", "1914", "1960", "1900"], answer: 0 },
    { id: 119, topic: "International Org", question: "Head of Commonwealth?", options: ["Nigeria", "UK", "USA", "Canada"], answer: 1 },
    { id: 120, topic: "Human Rights", question: "UDHR was adopted in?", options: ["1945", "1948", "1960", "1918"], answer: 1 }
  ],
  economics: [
    { id: 121, topic: "Fundamental Concepts", question: "Basic problem of economics?", options: ["Money", "Inflation", "Scarcity", "Trade"], answer: 2 },
    { id: 122, topic: "Elasticity", question: "Responsiveness of demand?", options: ["Supply", "Income", "Elasticity", "Taste"], answer: 2 },
    { id: 123, topic: "Fundamental Concepts", question: "Next best alternative foregone?", options: ["Price", "Scarcity", "Opportunity Cost", "Choice"], answer: 2 },
    { id: 124, topic: "Factors of Production", question: "Reward for labor?", options: ["Rent", "Wages", "Interest", "Profit"], answer: 1 },
    { id: 125, topic: "Markets", question: "Single seller market?", options: ["Monopoly", "Perfect", "Oligopoly", "Duopoly"], answer: 0 },
    { id: 126, topic: "Inflation", question: "Persistent rise in prices?", options: ["Deflation", "Inflation", "Stagflation", "Boom"], answer: 1 },
    { id: 127, topic: "National Income", question: "GDP full name?", options: ["Gross Dom. Prod", "General Dom. Price", "Govt Dom. Prod", "None"], answer: 0 },
    { id: 128, topic: "Money", question: "Standard medium of exchange?", options: ["Gold", "Money", "Barter", "Trade"], answer: 1 },
    { id: 129, topic: "Population", question: "Frequency of Census?", options: ["5 years", "10 years", "15 years", "20 years"], answer: 1 },
    { id: 130, topic: "Budget", question: "Revenue exceeds expenditure?", options: ["Deficit", "Surplus", "Balanced", "Debt"], answer: 1 },
    { id: 131, topic: "Utility", question: "Satisfaction derived?", options: ["Usefulness", "Utility", "Value", "Price"], answer: 1 },
    { id: 132, topic: "Supply", question: "Higher price, higher ___?", options: ["Demand", "Supply", "Scarcity", "Utility"], answer: 1 },
    { id: 133, topic: "Production", question: "Human effort in economy?", options: ["Capital", "Land", "Labor", "Firm"], answer: 2 },
    { id: 134, topic: "Taxation", question: "Example of direct tax?", options: ["VAT", "PAYE", "Excise", "Customs"], answer: 1 },
    { id: 135, topic: "Trade", question: "Exports exceed imports?", options: ["Trade deficit", "Trade surplus", "Equal trade", "Embargo"], answer: 1 },
    { id: 136, topic: "Banking", question: "Nigeria's banker's bank?", options: ["First Bank", "GTB", "CBN", "Zenith"], answer: 2 },
    { id: 137, topic: "Cost", question: "Total Cost = Fixed Cost + ___?", options: ["Variable Cost", "Marginal Cost", "Average Cost", "Total Revenue"], answer: 0 },
    { id: 138, topic: "Demand", question: "Law of demand curve?", options: ["Upward", "Downward", "Vertical", "Horizontal"], answer: 1 },
    { id: 139, topic: "Factors of Production", question: "Land reward is?", options: ["Labor", "Rent", "Capital", "Enterprise"], answer: 1 },
    { id: 140, topic: "Development", question: "HDI full form?", options: ["Human Dev Index", "High Dev Info", "Health Dev Index", "None"], answer: 0 }
  ],
  commerce: [
    { id: 141, topic: "Production", question: "Activity like mining?", options: ["Secondary", "Primary", "Tertiary", "Service"], answer: 1 },
    { id: 142, topic: "Documents", question: "Receipt of goods acknowledge?", options: ["Invoice", "Credit Note", "Delivery Note", "Waybill"], answer: 2 },
    { id: 143, topic: "Trade", question: "Goods for goods system?", options: ["Trade", "Commerce", "Barter", "Retail"], answer: 2 },
    { id: 144, topic: "Insurance", question: "Indemnity means?", options: ["Profit", "Restore to original", "Loss", "Gambling"], answer: 1 },
    { id: 145, topic: "Distribution", question: "Starts the channel?", options: ["Wholesaler", "Retailer", "Consumer", "Producer"], answer: 3 },
    { id: 146, topic: "Ownership", question: "Owned by one person?", options: ["Partnership", "Sole Prop.", "Ltd", "PLC"], answer: 1 },
    { id: 147, topic: "Banking", question: "ATM full name?", options: ["Automated Teller Machine", "Auto Teller Money", "Auto Ticket Money", "None"], answer: 0 },
    { id: 148, topic: "Marketing", question: "Branding purpose?", options: ["Production", "Identification", "Storage", "Transport"], answer: 1 },
    { id: 149, topic: "Transport", question: "Fastest transport mode?", options: ["Road", "Rail", "Water", "Air"], answer: 3 },
    { id: 150, topic: "Mass Media", question: "Radio communication type?", options: ["Visual", "Oral", "Mass Comm", "Written"], answer: 2 },
    { id: 151, topic: "Retail", question: "Sells in bits?", options: ["Wholesaler", "Producer", "Retailer", "Agent"], answer: 2 },
    { id: 152, topic: "Advertising", question: "Persuasion to buy?", options: ["Warehousing", "Advertising", "Invoicing", "Lending"], answer: 1 },
    { id: 153, topic: "Credit", question: "Buy now pay later?", options: ["Cash", "Credit", "Lease", "None"], answer: 1 },
    { id: 154, topic: "Company Law", question: "Prospectus is for?", options: ["Sole Trader", "Partnership", "Public Company", "Private Company"], answer: 2 },
    { id: 155, topic: "Warehousing", question: "Goods storage?", options: ["Distribution", "Warehousing", "Retail", "Wholesale"], answer: 1 },
    { id: 156, topic: "Money", question: "Nigeria legal tender?", options: ["Dollar", "Naira", "Pounds", "Euro"], answer: 1 },
    { id: 157, topic: "Agent", question: "Represents another?", options: ["Principal", "Agent", "Retailer", "Consumer"], answer: 1 },
    { id: 158, topic: "Industry", question: "Processing raw materials?", options: ["Primary", "Secondary", "Tertiary", "Direct"], answer: 1 },
    { id: 159, topic: "Trade", question: "Selling out of country?", options: ["Import", "Export", "Entrepôt", "Home Trade"], answer: 1 },
    { id: 160, topic: "Marketing", question: "Marketing 4Ps include?", options: ["Price, Product, Place, Promotion", "Power, Peace, Price, Plan", "Person, Place, Price, Power", "None"], answer: 0 }
  ],
  accounting: [
    { id: 161, topic: "Accounting Equation", question: "The equation is?", options: ["A = L - C", "A = L + C", "C = A + L", "L = C + A"], answer: 1 },
    { id: 162, topic: "Assets", question: "Most liquid asset?", options: ["Land", "Machinery", "Cash", "Goodwill"], answer: 2 },
    { id: 163, topic: "Books of Entry", question: "Book of final entry?", options: ["Journal", "Ledger", "Cash Book", "Invoice"], answer: 1 },
    { id: 164, topic: "Double Entry", question: "Cash purchase debit?", options: ["Sales", "Creditor", "Purchases", "Bank"], answer: 2 },
    { id: 165, topic: "Trial Balance", question: "Checks accuracy?", options: ["Balance Sheet", "Trial Balance", "Ledger", "Trading A/C"], answer: 1 },
    { id: 166, topic: "Fixed Assets", question: "Loss in asset value?", options: ["Appreciation", "Depreciation", "Inflation", "Bad debt"], answer: 1 },
    { id: 167, topic: "Petty Cash", question: "Uses imprest system?", options: ["Sales Book", "Petty Cash Book", "General Ledger", "Journal"], answer: 1 },
    { id: 168, topic: "Final Accounts", question: "Shows financial status?", options: ["Profit/Loss", "Trading A/C", "Balance Sheet", "Cash Book"], answer: 2 },
    { id: 169, topic: "Debtors/Creditors", question: "Owes the firm?", options: ["Creditor", "Debtor", "Owner", "Manager"], answer: 1 },
    { id: 170, topic: "Final Accounts", question: "Shows gross profit?", options: ["Profit/Loss", "Trading A/C", "Balance Sheet", "Statement"], answer: 1 },
    { id: 171, topic: "History", question: "Father of bookkeeping?", options: ["Adam Smith", "Luca Pacioli", "Keynes", "Ricardo"], answer: 1 },
    { id: 172, topic: "Errors", question: "Writing 54 as 45 is?", options: ["Transposition", "Omission", "Principle", "Commission"], answer: 0 },
    { id: 173, topic: "Profitability", question: "Net profit formula?", options: ["GP - Expenses", "GP + Expenses", "Sales - COGS", "COGS - GP"], answer: 0 },
    { id: 174, topic: "Bank Reconciliation", question: "Unpresented check is?", options: ["Not in cash book", "Not in statement", "Expired", "Bounced"], answer: 1 },
    { id: 175, topic: "Intangible Assets", question: "Example of intangible?", options: ["Cash", "Buildings", "Goodwill", "Stock"], answer: 2 },
    { id: 176, topic: "Working Capital", question: "Working capital =?", options: ["CA - CL", "CA + CL", "FA - CL", "Assets - CL"], answer: 0 },
    { id: 177, topic: "Cash Book", question: "3-column cash book has?", options: ["Discount, Cash, Bank", "Sales, Cash, Bank", "Cash, Creditor, Bank", "None"], answer: 0 },
    { id: 178, topic: "Adjustments", question: "Expenses owed?", options: ["Prepayment", "Accrual", "Asset", "Revenue"], answer: 1 },
    { id: 179, topic: "Double Entry", question: "Debit the?", options: ["Giver", "Receiver", "Owner", "Accountant"], answer: 1 },
    { id: 180, topic: "Control Accounts", question: "Check on ledgers?", options: ["Control A/C", "Suspense A/C", "Trial Balance", "Trading A/C"], answer: 0 }
  ],
  literature: [
    { id: 181, topic: "Poetry", question: "14-line poem?", options: ["Ode", "Elegy", "Sonnet", "Epic"], answer: 2 },
    { id: 182, topic: "Drama", question: "Funny play?", options: ["Tragedy", "Comedy", "Farce", "Satire"], answer: 1 },
    { id: 183, topic: "Devices", question: "No like/as comparison?", options: ["Simile", "Metaphor", "Personification", "Hyperbole"], answer: 1 },
    { id: 184, topic: "Characters", question: "The story hero?", options: ["Antagonist", "Protagonist", "Villain", "Narrator"], answer: 1 },
    { id: 185, topic: "Narrative", question: "Own life story?", options: ["Biography", "Autobiography", "Anthology", "Epic"], answer: 1 },
    { id: 186, topic: "Devices", question: "Human traits to objects?", options: ["Simile", "Metaphor", "Personification", "Irony"], answer: 2 },
    { id: 187, topic: "Setting", question: "Time and place?", options: ["Plot", "Setting", "Theme", "Tone"], answer: 1 },
    { id: 188, topic: "African Lit", question: "'Things Fall Apart' author?", options: ["Soyinka", "Achebe", "Nwapa", "Emecheta"], answer: 1 },
    { id: 189, topic: "Poetry", question: "Mourning poem?", options: ["Ode", "Elegy", "Lyric", "Sonnet"], answer: 1 },
    { id: 190, topic: "Devices", question: "Words sounding like sounds?", options: ["Assonance", "Onomatopoeia", "Pun", "Irony"], answer: 1 },
    { id: 191, topic: "Drama", question: "Long speech by one?", options: ["Dialogue", "Monologue", "Soliloquy", "Prologue"], answer: 1 },
    { id: 192, topic: "Genres", question: "Moral animal story?", options: ["Fable", "Myth", "Legend", "Epic"], answer: 0 },
    { id: 193, topic: "Structure", question: "Turning point?", options: ["Climax", "Resolution", "Conflict", "Exposition"], answer: 0 },
    { id: 194, topic: "Devices", question: "Consonant repetition?", options: ["Alliteration", "Assonance", "Rhyme", "Meter"], answer: 0 },
    { id: 195, topic: "Drama", question: "Play introduction?", options: ["Epilogue", "Prologue", "Climax", "Scene"], answer: 1 },
    { id: 196, topic: "Devices", question: "Extreme exaggeration?", options: ["Irony", "Hyperbole", "Oxymoron", "Simile"], answer: 1 },
    { id: 197, topic: "Poetry", question: "4-line stanza?", options: ["Couplet", "Quatrain", "Sestet", "Octave"], answer: 1 },
    { id: 198, topic: "Devices", question: "Opposites together?", options: ["Metaphor", "Oxymoron", "Simile", "Pun"], answer: 1 },
    { id: 199, topic: "African Lit", question: "1st African Nobel Literature?", options: ["Achebe", "Soyinka", "Ngugi", "Armah"], answer: 1 },
    { id: 200, topic: "Prose", question: "A novel is?", options: ["Poetry", "Prose", "Drama", "Oral"], answer: 1 }
  ],
  crs: [
    { id: 201, topic: "Creation", question: "Days of creation?", options: ["5", "6", "7", "8"], answer: 1 },
    { id: 202, topic: "Patriarchs", question: "Father of faithful?", options: ["Moses", "Abraham", "David", "Isaac"], answer: 1 },
    { id: 203, topic: "Early History", question: "The 1st murder?", options: ["Adam", "Cain", "Abel", "Seth"], answer: 1 },
    { id: 204, topic: "Exodus", question: "Leader from Egypt?", options: ["Joshua", "Aaron", "Moses", "Joseph"], answer: 2 },
    { id: 205, topic: "Prophets", question: "Swallowed by fish?", options: ["Peter", "Jonah", "Paul", "Noah"], answer: 1 },
    { id: 206, topic: "Gospels", question: "Birthplace of Jesus?", options: ["Nazareth", "Jerusalem", "Bethlehem", "Galilee"], answer: 2 },
    { id: 207, topic: "Monarchy", question: "1st King of Israel?", options: ["David", "Saul", "Solomon", "Samuel"], answer: 1 },
    { id: 208, topic: "Judges", question: "Strongest man?", options: ["Samson", "David", "Goliath", "Solomon"], answer: 0 },
    { id: 209, topic: "Gospels", question: "Betrayer of Jesus?", options: ["Peter", "John", "Judas", "Thomas"], answer: 2 },
    { id: 210, topic: "Scripture", question: "1st Bible book?", options: ["Exodus", "Matthew", "Genesis", "Revelation"], answer: 2 },
    { id: 211, topic: "Monarchy", question: "Wisest king?", options: ["Saul", "David", "Solomon", "Hezekiah"], answer: 2 },
    { id: 212, topic: "Prophets", question: "Mt. Carmel prophet?", options: ["Elisha", "Elijah", "Isaiah", "Jeremiah"], answer: 1 },
    { id: 213, topic: "Exodus", question: "Moses divided the?", options: ["Dead Sea", "Red Sea", "Galilee", "Jordan"], answer: 1 },
    { id: 214, topic: "Creation", question: "The first man?", options: ["Noah", "Adam", "Abel", "Seth"], answer: 1 },
    { id: 215, topic: "Law", question: "Commandments given at?", options: ["Mt. Sinai", "Mt. Nebo", "Mt. Zion", "Mt. Carmel"], answer: 0 },
    { id: 216, topic: "Teachings", question: "Jesus taught in?", options: ["Fables", "Parables", "Poetry", "Essays"], answer: 1 },
    { id: 217, topic: "Apostles", question: "Doubting apostle?", options: ["Peter", "John", "Thomas", "Andrew"], answer: 2 },
    { id: 218, topic: "Gospels", question: "Mother of Jesus?", options: ["Martha", "Mary", "Elizabeth", "Ruth"], answer: 1 },
    { id: 219, topic: "Scripture", question: "Last Bible book?", options: ["Genesis", "Acts", "Revelation", "Malachi"], answer: 2 },
    { id: 220, topic: "Noah", question: "Flood survivor?", options: ["Lot", "Noah", "Abraham", "Isaac"], answer: 1 }
  ]
};
