const questionBank = {
    math: [
        { question: "Solve for x: 2x + 5 = 15", options: ["5", "10", "15", "20"], answer: 0, topic: "Algebra" },
        { question: "What is the square root of 144?", options: ["10", "11", "12", "13"], answer: 2, topic: "Arithmetic" },
        { question: "Find the median of 2, 4, 7, 8, 9", options: ["4", "7", "8", "9"], answer: 1, topic: "Statistics" },
        { question: "Calculate the area of a circle with radius 7cm (π=22/7)", options: ["154cm²", "44cm²", "49cm²", "77cm²"], answer: 0, topic: "Mensuration" },
        { question: "If sin θ = 0.5, find θ", options: ["30°", "45°", "60°", "90°"], answer: 0, topic: "Trigonometry" },
        { question: "Simplify: (2^3) * (2^2)", options: ["2^1", "2^5", "2^6", "4^5"], answer: 1, topic: "Indices" },
        { question: "Find the slope of the line y = 3x + 5", options: ["5", "3", "-3", "1/3"], answer: 1, topic: "Coordinate Geometry" },
        { question: "Solve for y: 3y - 9 = 0", options: ["1", "2", "3", "0"], answer: 2, topic: "Algebra" },
        { question: "What is 15% of 200?", options: ["20", "25", "30", "40"], answer: 2, topic: "Percentage" },
        { question: "Calculate the simple interest on #1000 at 5% for 2 years", options: ["#100", "#50", "#200", "#150"], answer: 0, topic: "Financial Math" },
        { question: "Evaluate: Log10(100)", options: ["1", "2", "10", "0"], answer: 1, topic: "Logarithms" },
        { question: "Find the mean of 10, 20, 30", options: ["10", "15", "20", "25"], answer: 2, topic: "Statistics" },
        { question: "A triangle with all sides equal is called?", options: ["Isosceles", "Scalene", "Equilateral", "Right-angled"], answer: 2, topic: "Geometry" },
        { question: "Find the value of x if x² = 64", options: ["4", "6", "8", "12"], answer: 2, topic: "Algebra" },
        { question: "Expand (x+2)(x-2)", options: ["x²+4", "x²-4", "x²-4x+4", "x²+4x+4"], answer: 1, topic: "Expansion" },
        { question: "What is the sum of angles in a triangle?", options: ["90°", "180°", "270°", "360°"], answer: 1, topic: "Geometry" },
        { question: "Convert 0.25 to a fraction", options: ["1/2", "1/4", "1/5", "1/8"], answer: 1, topic: "Fractions" },
        { question: "Calculate the volume of a cube with side 3cm", options: ["9cm³", "18cm³", "27cm³", "81cm³"], answer: 2, topic: "Mensuration" },
        { question: "Factorize: x² + 5x + 6", options: ["(x+1)(x+6)", "(x+2)(x+3)", "(x-2)(x-3)", "(x+5)(x+1)"], answer: 1, topic: "Factorization" },
        { question: "What is the HCF of 12 and 18?", options: ["2", "3", "6", "12"], answer: 2, topic: "Arithmetic" },
        { question: "Solve: 5 - ( -3 )", options: ["2", "8", "-8", "-2"], answer: 1, topic: "Arithmetic" },
        { question: "Find the mode: 1, 2, 2, 3, 4", options: ["1", "2", "3", "4"], answer: 1, topic: "Statistics" },
        { question: "What is the value of π (Pi) approximately?", options: ["2.14", "3.14", "3.41", "4.13"], answer: 1, topic: "Mensuration" },
        { question: "If 4x = 12, what is 2x?", options: ["3", "6", "8", "24"], answer: 1, topic: "Algebra" },
        { question: "What is the perimeter of a square with side 5cm?", options: ["10cm", "20cm", "25cm", "15cm"], answer: 1, topic: "Geometry" },
        { question: "The probability of a sure event is?", options: ["0", "0.5", "1", "-1"], answer: 2, topic: "Probability" },
        { question: "Solve for x: x/2 = 10", options: ["5", "10", "20", "40"], answer: 2, topic: "Algebra" },
        { question: "What is the product of 1.2 and 0.5?", options: ["0.6", "6.0", "0.06", "1.7"], answer: 0, topic: "Decimals" },
        { question: "A polygon with 5 sides is a?", options: ["Hexagon", "Pentagon", "Heptagon", "Octagon"], answer: 1, topic: "Geometry" },
        { question: "Simplify: √50", options: ["5√2", "2√5", "10√2", "25√2"], answer: 0, topic: "Surds" },
        { question: "Find the 4th term in the sequence: 2, 4, 6...", options: ["7", "8", "9", "10"], answer: 1, topic: "Sequences" },
        { question: "If a=2 and b=3, find a² + b", options: ["5", "7", "11", "13"], answer: 1, topic: "Substitution" },
        { question: "What is the supplement of 60°?", options: ["30°", "120°", "180°", "90°"], answer: 1, topic: "Geometry" },
        { question: "Find the LCM of 4 and 6", options: ["10", "12", "24", "48"], answer: 1, topic: "Arithmetic" },
        { question: "How many degrees are in a circle?", options: ["180°", "270°", "360°", "450°"], answer: 2, topic: "Geometry" },
        { question: "Simplify: (x³)²", options: ["x^5", "x^6", "x^9", "2x³"], answer: 1, topic: "Indices" },
        { question: "Change 2/5 to percentage", options: ["20%", "40%", "50%", "60%"], answer: 1, topic: "Percentage" },
        { question: "If x + y = 10 and x - y = 2, find x", options: ["4", "6", "8", "12"], answer: 1, topic: "Simultaneous Eq" },
        { question: "Calculate the diagonal of a rectangle (3cm by 4cm)", options: ["5cm", "7cm", "12cm", "25cm"], answer: 0, topic: "Pythagoras" },
        { question: "The derivative of x² is?", options: ["x", "2x", "2", "x³"], answer: 1, topic: "Calculus" }
    ],
    english: [
        { question: "Choose the nearest in meaning: ADVERSITY", options: ["Happiness", "Misfortune", "Wealth", "Progress"], answer: 1, topic: "Synonyms" },
        { question: "Choose the opposite: OPTIMISTIC", options: ["Hopeful", "Pessimistic", "Cheerful", "Careless"], answer: 1, topic: "Antonyms" },
        { question: "She ___ to school every day.", options: ["go", "goes", "going", "gone"], answer: 1, topic: "Tenses" },
        { question: "Identify the noun: 'The silence was deafening.'", options: ["Silence", "Was", "Deafening", "The"], answer: 0, topic: "Parts of Speech" },
        { question: "A person who writes books is an?", options: ["Actor", "Author", "Artist", "Architect"], answer: 1, topic: "Vocabulary" },
        { question: "Choose the correct spelling:", options: ["Accomodation", "Accommodation", "Acomodation", "Accommadation"], answer: 1, topic: "Spelling" },
        { question: "Neither the boys nor the girl ___ present.", options: ["are", "is", "were", "been"], answer: 1, topic: "Concord" },
        { question: "He is the ___ of the two brothers.", options: ["tall", "taller", "tallest", "more tall"], answer: 1, topic: "Adjectives" },
        { question: "The cat jumped ___ the fence.", options: ["over", "under", "in", "through"], answer: 0, topic: "Prepositions" },
        { question: "Choose the synonym: ENORMOUS", options: ["Small", "Huge", "Soft", "Weak"], answer: 1, topic: "Synonyms" },
        { question: "The plural of 'Child' is?", options: ["Childs", "Childrens", "Children", "Childes"], answer: 2, topic: "Nouns" },
        { question: "I have been waiting here ___ two hours.", options: ["since", "for", "from", "at"], answer: 1, topic: "Prepositions" },
        { question: "Choose the antonym: ARTIFICIAL", options: ["Man-made", "Natural", "Fake", "Modern"], answer: 1, topic: "Antonyms" },
        { question: "Which of these is a vowel?", options: ["B", "E", "G", "H"], answer: 1, topic: "Phonetics" },
        { question: "The boy ___ stole the pen was caught.", options: ["which", "who", "whom", "whose"], answer: 1, topic: "Pronouns" },
        { question: "They ___ finished their homework already.", options: ["has", "have", "had", "having"], answer: 1, topic: "Tenses" },
        { question: "Choose the nearest in meaning: RELUCTANT", options: ["Willing", "Unwilling", "Ready", "Eager"], answer: 1, topic: "Synonyms" },
        { question: "The sun ___ in the East.", options: ["rise", "rises", "rising", "rose"], answer: 1, topic: "Tenses" },
        { question: "Pick the odd word out:", options: ["Table", "Chair", "Sofa", "Water"], answer: 3, topic: "Vocabulary" },
        { question: "A story of a person's life written by another is?", options: ["Autobiography", "Biography", "Novel", "History"], answer: 1, topic: "Literature Terms" },
        { question: "The cake was shared ___ the two friends.", options: ["among", "between", "beside", "along"], answer: 1, topic: "Prepositions" },
        { question: "Choose the correct spelling:", options: ["Receive", "Recieve", "Receve", "Reseive"], answer: 0, topic: "Spelling" },
        { question: "He is as brave as a ___", options: ["Sheep", "Lion", "Cat", "Ant"], answer: 1, topic: "Similes" },
        { question: "I ___ a movie when the lights went out.", options: ["watch", "am watching", "was watching", "watched"], answer: 2, topic: "Tenses" },
        { question: "The opposite of 'Ancient' is?", options: ["Old", "Modern", "Antique", "Past"], answer: 1, topic: "Antonyms" },
        { question: "Which of these is a conjunction?", options: ["But", "Fast", "Jump", "Slow"], answer: 0, topic: "Parts of Speech" },
        { question: "If I ___ you, I would go.", options: ["am", "was", "were", "be"], answer: 2, topic: "Conditionals" },
        { question: "The sound made by a cow is called?", options: ["Bark", "Moo", "Bleat", "Hiss"], answer: 1, topic: "Vocabulary" },
        { question: "The synonym of 'Courageous' is?", options: ["Brave", "Cowardly", "Shy", "Quiet"], answer: 0, topic: "Synonyms" },
        { question: "This is my ___ bag.", options: ["sister", "sisters", "sister's", "sisters's"], answer: 2, topic: "Possessives" },
        { question: "The antonym of 'Victory' is?", options: ["Win", "Success", "Defeat", "Gain"], answer: 2, topic: "Antonyms" },
        { question: "We go to church ___ Sundays.", options: ["on", "at", "in", "by"], answer: 0, topic: "Prepositions" },
        { question: "Which of these is an adverb?", options: ["Beautiful", "Quickly", "Boy", "Run"], answer: 1, topic: "Parts of Speech" },
        { question: "I forgot my umbrella, ___ I got wet.", options: ["so", "but", "because", "since"], answer: 0, topic: "Conjunctions" },
        { question: "What is the past tense of 'Eat'?", options: ["Eaten", "Eating", "Ate", "Eats"], answer: 2, topic: "Tenses" },
        { question: "The group of people watching a game are?", options: ["Audience", "Spectators", "Crowd", "Congregation"], answer: 1, topic: "Collective Nouns" },
        { question: "Choose the word with different stress: EDUCATION", options: ["ED-u-ca-tion", "ed-U-ca-tion", "ed-u-CA-tion", "ed-u-ca-TION"], answer: 2, topic: "Stress" },
        { question: "Identify the adjective: 'The red car is fast.'", options: ["Red", "Car", "Is", "Fast"], answer: 0, topic: "Parts of Speech" },
        { question: "The idiom 'To kick the bucket' means?", options: ["To play", "To die", "To dance", "To sing"], answer: 1, topic: "Idioms" },
        { question: "Choose the correct article: ___ umbrella is useful.", options: ["A", "An", "The", "None"], answer: 1, topic: "Articles" }
    ],
    physics: [
        { question: "The unit of electric current is?", options: ["Volt", "Ohm", "Ampere", "Watt"], answer: 2, topic: "Electricity" },
        { question: "Velocity is a ___ quantity.", options: ["Scalar", "Vector", "Dimensionless", "Constant"], answer: 1, topic: "Motion" },
        { question: "What is the acceleration due to gravity on Earth?", options: ["5.8 m/s²", "9.8 m/s²", "12 m/s²", "0 m/s²"], answer: 1, topic: "Gravitation" },
        { question: "Which mirror is used as a driving mirror?", options: ["Plane", "Concave", "Convex", "Cylindrical"], answer: 2, topic: "Optics" },
        { question: "The boiling point of pure water in Celsius is?", options: ["0°C", "50°C", "100°C", "212°C"], answer: 2, topic: "Heat" },
        { question: "Density is defined as?", options: ["Mass x Volume", "Volume / Mass", "Mass / Volume", "Weight / Volume"], answer: 2, topic: "Matter" },
        { question: "Work done is measured in?", options: ["Watts", "Newtons", "Joules", "Pascal"], answer: 2, topic: "Work/Energy" },
        { question: "What type of wave is sound?", options: ["Transverse", "Longitudinal", "Electromagnetic", "Radio"], answer: 1, topic: "Waves" },
        { question: "The instrument used to measure atmospheric pressure is?", options: ["Thermometer", "Hygrometer", "Barometer", "Ammeter"], answer: 2, topic: "Fluids" },
        { question: "Ohms Law states V = ?", options: ["I/R", "I + R", "I * R", "R/I"], answer: 2, topic: "Electricity" },
        { question: "Which of these is a good conductor of heat?", options: ["Wood", "Plastic", "Copper", "Rubber"], answer: 2, topic: "Heat" },
        { question: "The speed of light is approximately?", options: ["3 x 10^8 m/s", "3 x 10^6 m/s", "300 m/s", "1500 m/s"], answer: 0, topic: "Optics" },
        { question: "Newton's first law is also known as law of?", options: ["Force", "Inertia", "Action", "Gravity"], answer: 1, topic: "Mechanics" },
        { question: "Energy possessed by a body in motion is?", options: ["Potential", "Kinetic", "Chemical", "Solar"], answer: 1, topic: "Work/Energy" },
        { question: "The process of heat transfer in solids is?", options: ["Convection", "Radiation", "Conduction", "Evaporation"], answer: 2, topic: "Heat" },
        { question: "What is the unit of power?", options: ["Joule", "Watt", "Newton", "Volt"], answer: 1, topic: "Work/Energy" },
        { question: "The change in position of a body with time is?", options: ["Speed", "Velocity", "Motion", "Acceleration"], answer: 2, topic: "Motion" },
        { question: "An object that allows light to pass through partially is?", options: ["Opaque", "Transparent", "Translucent", "Luminous"], answer: 2, topic: "Optics" },
        { question: "Pressure is defined as?", options: ["Force / Area", "Area / Force", "Force x Area", "Mass / Area"], answer: 0, topic: "Mechanics" },
        { question: "The focal length of a lens is measured in?", options: ["Degrees", "Meters", "Amperes", "Joules"], answer: 1, topic: "Optics" },
        { question: "Which subatomic particle has a negative charge?", options: ["Proton", "Neutron", "Electron", "Nucleus"], answer: 2, topic: "Atomic Physics" },
        { question: "Resistance is measured in?", options: ["Volts", "Ohms", "Watts", "Farads"], answer: 1, topic: "Electricity" },
        { question: "A body at rest has zero ___", options: ["Mass", "Weight", "Kinetic Energy", "Potential Energy"], answer: 2, topic: "Work/Energy" },
        { question: "The color of light with the longest wavelength is?", options: ["Violet", "Blue", "Green", "Red"], answer: 3, topic: "Optics" },
        { question: "The SI unit of Temperature is?", options: ["Celsius", "Fahrenheit", "Kelvin", "Rankine"], answer: 2, topic: "Heat" },
        { question: "Momentum is the product of mass and ___", options: ["Force", "Velocity", "Time", "Acceleration"], answer: 1, topic: "Mechanics" },
        { question: "Which of these is an primary cell?", options: ["Leclanche cell", "Lead-acid battery", "Inverter", "Generator"], answer: 0, topic: "Electricity" },
        { question: "Surface tension is responsible for?", options: ["Viscosity", "Drops forming", "Evaporation", "Boiling"], answer: 1, topic: "Matter" },
        { question: "A machine with 100% efficiency is called?", options: ["Perfect machine", "Ideal machine", "Real machine", "Simple machine"], answer: 1, topic: "Mechanics" },
        { question: "Upthrust is equal to the weight of fluid displaced is ___ principle.", options: ["Pascal", "Archimedes", "Newton", "Boyle"], answer: 1, topic: "Fluids" },
        { question: "The pitch of a sound depends on?", options: ["Amplitude", "Frequency", "Wavelength", "Loudness"], answer: 1, topic: "Waves" },
        { question: "The time taken for one complete oscillation is?", options: ["Frequency", "Period", "Amplitude", "Speed"], answer: 1, topic: "Waves" },
        { question: "Atmospheric pressure at sea level is about?", options: ["760 mmHg", "100 mmHg", "0 mmHg", "1000 mmHg"], answer: 0, topic: "Fluids" },
        { question: "Which of these is a scalar quantity?", options: ["Displacement", "Weight", "Mass", "Acceleration"], answer: 2, topic: "Mechanics" },
        { question: "Heat from the sun reaches Earth by?", options: ["Conduction", "Convection", "Radiation", "Insulation"], answer: 2, topic: "Heat" },
        { question: "Capacitance is measured in?", options: ["Ohms", "Farads", "Henrys", "Teslas"], answer: 1, topic: "Electricity" },
        { question: "The normal human body temperature is about?", options: ["37°C", "98°C", "45°C", "32°C"], answer: 0, topic: "Heat" },
        { question: "Radio waves travel at the speed of ___", options: ["Sound", "Light", "Wind", "Water"], answer: 1, topic: "Waves" },
        { question: "A clinical thermometer has a ___ to prevent backflow.", options: ["Bulb", "Stem", "Constriction", "Scale"], answer: 2, topic: "Heat" },
        { question: "Force = mass x ___", options: ["Speed", "Velocity", "Acceleration", "Time"], answer: 2, topic: "Mechanics" }
    ],
    chemistry: [
        { question: "What is the atomic number of Hydrogen?", options: ["1", "2", "3", "4"], answer: 0, topic: "Atomic Structure" },
        { question: "The PH of a neutral substance like water is?", options: ["0", "7", "14", "1"], answer: 1, topic: "Acids & Bases" },
        { question: "Which gas is used in fire extinguishers?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], answer: 2, topic: "Gases" },
        { question: "The symbol 'Fe' stands for?", options: ["Fluorine", "Iron", "Gold", "Lead"], answer: 1, topic: "Periodic Table" },
        { question: "Rusting of iron requires moisture and ___", options: ["Nitrogen", "Oxygen", "Carbon", "Helium"], answer: 1, topic: "Corrosion" },
        { question: "The simplest organic compound is?", options: ["Ethane", "Methane", "Propane", "Butane"], answer: 1, topic: "Organic Chemistry" },
        { question: "A substance that speeds up a chemical reaction is a?", options: ["Reactant", "Product", "Catalyst", "Inhibitor"], answer: 2, topic: "Reactions" },
        { question: "What is the most abundant gas in the atmosphere?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"], answer: 2, topic: "Atmosphere" },
        { question: "The bond formed by sharing electrons is?", options: ["Ionic", "Covalent", "Metallic", "Hydrogen"], answer: 1, topic: "Bonding" },
        { question: "Which acid is found in car batteries?", options: ["HCl", "H2SO4", "HNO3", "CH3COOH"], answer: 1, topic: "Acids & Bases" },
        { question: "The horizontal rows of the periodic table are?", options: ["Groups", "Families", "Periods", "Blocks"], answer: 2, topic: "Periodic Table" },
        { question: "Hard water does not lather easily with ___", options: ["Soap", "Detergent", "Salt", "Sugar"], answer: 0, topic: "Water" },
        { question: "Avogadro's number is?", options: ["6.02x10^23", "3.02x10^23", "1.02x10^10", "6.02x10^20"], answer: 0, topic: "Mole Concept" },
        { question: "What is the mass number of an atom with 6 protons and 6 neutrons?", options: ["6", "12", "18", "0"], answer: 1, topic: "Atomic Structure" },
        { question: "Valency of Oxygen is?", options: ["1", "2", "3", "4"], answer: 1, topic: "Valency" },
        { question: "An atom that has lost or gained electrons is an?", options: ["Isotope", "Ion", "Molecule", "Element"], answer: 1, topic: "Atomic Structure" },
        { question: "Which of these is a noble gas?", options: ["Chlorine", "Neon", "Oxygen", "Fluorine"], answer: 1, topic: "Periodic Table" },
        { question: "Combustion is a reaction with ___", options: ["Water", "Oxygen", "Nitrogen", "Hydrogen"], answer: 1, topic: "Reactions" },
        { question: "Common salt is chemically known as?", options: ["Sodium Hydroxide", "Sodium Chloride", "Sodium Carbonate", "Sodium Nitrate"], answer: 1, topic: "Salts" },
        { question: "Which element is common to all organic compounds?", options: ["Oxygen", "Nitrogen", "Carbon", "Sulfur"], answer: 2, topic: "Organic Chemistry" },
        { question: "The process of a solid turning directly into gas is?", options: ["Evaporation", "Sublimation", "Condensation", "Freezing"], answer: 1, topic: "Matter" },
        { question: "A base that dissolves in water is called an?", options: ["Acid", "Alkali", "Salt", "Oxide"], answer: 1, topic: "Acids & Bases" },
        { question: "Brass is an alloy of Copper and ___", options: ["Zinc", "Tin", "Iron", "Lead"], answer: 0, topic: "Alloys" },
        { question: "The empirical formula of Benzene (C6H6) is?", options: ["C2H2", "CH", "C3H3", "C6H6"], answer: 1, topic: "Formulas" },
        { question: "Diamond and Graphite are ___ of Carbon.", options: ["Isotopes", "Allotropes", "Isomers", "Homologues"], answer: 1, topic: "Carbon" },
        { question: "The charge of a proton is?", options: ["Negative", "Neutral", "Positive", "Varies"], answer: 2, topic: "Atomic Structure" },
        { question: "What gas is evolved when zinc reacts with HCl?", options: ["Oxygen", "Chlorine", "Hydrogen", "Nitrogen"], answer: 2, topic: "Reactions" },
        { question: "The major constituent of natural gas is?", options: ["Ethane", "Methane", "Propane", "Butane"], answer: 1, topic: "Organic Chemistry" },
        { question: "Saponification is the process of making?", options: ["Salt", "Sugar", "Soap", "Glass"], answer: 2, topic: "Organic Chemistry" },
        { question: "Which metal is liquid at room temperature?", options: ["Mercury", "Gallium", "Sodium", "Lead"], answer: 0, topic: "Metals" },
        { question: "The universal solvent is?", options: ["Ethanol", "Water", "Acetone", "Benzene"], answer: 1, topic: "Water" },
        { question: "Isotopes have the same number of ___", options: ["Neutrons", "Electrons", "Protons", "Nucleons"], answer: 2, topic: "Isotopes" },
        { question: "What is the formula for Ammonia?", options: ["NH4", "NH3", "NO2", "HNO3"], answer: 1, topic: "Compounds" },
        { question: "A solution with PH 2 is?", options: ["Weakly Acidic", "Strongly Acidic", "Neutral", "Alkaline"], answer: 1, topic: "Acids & Bases" },
        { question: "Which gas turns lime water milky?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], answer: 1, topic: "Gases" },
        { question: "Reduction is the ___ of electrons.", options: ["Loss", "Gain", "Sharing", "Creation"], answer: 1, topic: "Redox" },
        { question: "The functional group -OH belongs to?", options: ["Alkanes", "Alkanols", "Alkanoic acids", "Alkenes"], answer: 1, topic: "Organic Chemistry" },
        { question: "Standard Temperature and Pressure (STP) volume of a gas is?", options: ["22.4 dm³", "10.0 dm³", "44.8 dm³", "2.24 dm³"], answer: 0, topic: "Mole Concept" },
        { question: "Which element is used in vulcanizing rubber?", options: ["Nitrogen", "Sulfur", "Phosphorus", "Carbon"], answer: 1, topic: "Non-metals" },
        { question: "The chemical formula for Chalk is?", options: ["CaO", "Ca(OH)2", "CaCO3", "CaCl2"], answer: 2, topic: "Compounds" }
    ],
    biology: [
        { question: "The basic unit of life is the?", options: ["Tissue", "Organ", "Cell", "System"], answer: 2, topic: "Cell Biology" },
        { question: "Which organelle is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Vacuole"], answer: 2, topic: "Cell Biology" },
        { question: "The green pigment in plants is?", options: ["Hemoglobin", "Chlorophyll", "Melanin", "Xanthophyll"], answer: 1, topic: "Photosynthesis" },
        { question: "Humans have ___ pairs of chromosomes.", options: ["20", "23", "46", "44"], answer: 1, topic: "Genetics" },
        { question: "Which vitamin is obtained from sunlight?", options: ["A", "B", "C", "D"], answer: 3, topic: "Nutrition" },
        { question: "The process by which plants make food is?", options: ["Respiration", "Digestion", "Photosynthesis", "Transpiration"], answer: 2, topic: "Plant Physiology" },
        { question: "Which blood group is the universal donor?", options: ["A", "B", "AB", "O"], answer: 3, topic: "Circulatory System" },
        { question: "The organ responsible for pumping blood is the?", options: ["Lungs", "Brain", "Heart", "Kidney"], answer: 2, topic: "Circulatory System" },
        { question: "The largest organ in the human body is the?", options: ["Liver", "Skin", "Brain", "Large Intestine"], answer: 1, topic: "Human Systems" },
        { question: "Which gas do plants absorb during photosynthesis?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], answer: 1, topic: "Photosynthesis" },
        { question: "The small pores on leaves for gas exchange are?", options: ["Veins", "Stomata", "Roots", "Petals"], answer: 1, topic: "Plant Anatomy" },
        { question: "A group of similar cells performing a function is a?", options: ["Organ", "System", "Tissue", "Organism"], answer: 2, topic: "Organization" },
        { question: "The bones of the spine are called?", options: ["Femur", "Ribs", "Vertebrae", "Skull"], answer: 2, topic: "Skeletal System" },
        { question: "Which part of the brain controls balance?", options: ["Cerebrum", "Cerebellum", "Medulla", "Thalamus"], answer: 1, topic: "Nervous System" },
        { question: "The movement of water across a semi-permeable membrane is?", options: ["Diffusion", "Osmosis", "Active Transport", "Evaporation"], answer: 1, topic: "Cell Transport" },
        { question: "Which enzyme is found in saliva?", options: ["Pepsin", "Lipase", "Ptaylin", "Trypsin"], answer: 2, topic: "Digestive System" },
        { question: "Animals without backbones are called?", options: ["Vertebrates", "Invertebrates", "Mammals", "Reptiles"], answer: 1, topic: "Classification" },
        { question: "The male reproductive part of a flower is the?", options: ["Stigma", "Style", "Stamen", "Ovary"], answer: 2, topic: "Reproduction" },
        { question: "Disease-causing organisms are called?", options: ["Antibiotics", "Pathogens", "Vaccines", "Symptoms"], answer: 1, topic: "Health" },
        { question: "The study of heredity is?", options: ["Ecology", "Genetics", "Botany", "Zoology"], answer: 1, topic: "Genetics" },
        { question: "The removal of metabolic waste from the body is?", options: ["Egestion", "Excretion", "Secretions", "Digestion"], answer: 1, topic: "Excretion" },
        { question: "The 'Master Gland' of the endocrine system is?", options: ["Thyroid", "Adrenal", "Pituitary", "Pancreas"], answer: 2, topic: "Hormones" },
        { question: "The clear liquid part of blood is?", options: ["Plasma", "Platelets", "RBC", "WBC"], answer: 0, topic: "Circulatory System" },
        { question: "Which of these is a flightless bird?", options: ["Eagle", "Ostrich", "Parrot", "Pigeon"], answer: 1, topic: "Classification" },
        { question: "The sensory organ for hearing is the?", options: ["Nose", "Tongue", "Ear", "Eye"], answer: 2, topic: "Senses" },
        { question: "Carbon monoxide is dangerous because it binds to?", options: ["White cells", "Hemoglobin", "Platelets", "Plasma"], answer: 1, topic: "Respiratory System" },
        { question: "Aerobic respiration requires ___", options: ["Water", "Carbon dioxide", "Oxygen", "Light"], answer: 2, topic: "Respiration" },
        { question: "Fungi reproduce mainly by?", options: ["Seeds", "Budding", "Spores", "Flowers"], answer: 2, topic: "Reproduction" },
        { question: "The habitat of an organism is its?", options: ["Food", "Home", "Climate", "Community"], answer: 1, topic: "Ecology" },
        { question: "Which vitamin helps in blood clotting?", options: ["A", "C", "D", "K"], answer: 3, topic: "Nutrition" },
        { question: "The main organ of respiration in fish is?", options: ["Lungs", "Gills", "Skin", "Trachea"], answer: 1, topic: "Respiration" },
        { question: "The sequence 'Who eats whom' in an ecosystem is?", options: ["Food web", "Food chain", "Ecological pyramid", "Niche"], answer: 1, topic: "Ecology" },
        { question: "Diabetes is caused by lack of ___", options: ["Adrenaline", "Thyroxine", "Insulin", "Estrogen"], answer: 2, topic: "Hormones" },
        { question: "The waste product of photosynthesis is?", options: ["Glucose", "Carbon dioxide", "Oxygen", "Water"], answer: 2, topic: "Photosynthesis" },
        { question: "Scurvy is caused by deficiency of Vitamin ___", options: ["A", "B", "C", "D"], answer: 2, topic: "Nutrition" },
        { question: "The knee joint is an example of a ___ joint.", options: ["Ball and socket", "Hinge", "Pivot", "Fixed"], answer: 1, topic: "Skeletal System" },
        { question: "Amphibians live ___", options: ["Only in water", "Only on land", "Both land and water", "In trees"], answer: 2, topic: "Classification" },
        { question: "The colored part of the eye is the?", options: ["Pupil", "Retina", "Iris", "Lens"], answer: 2, topic: "Senses" },
        { question: "Pollination by wind is called?", options: ["Entomophily", "Anemophily", "Hydrophily", "Zoophily"], answer: 1, topic: "Reproduction" },
        { question: "The study of plants is?", options: ["Zoology", "Botany", "Ecology", "Microbiology"], answer: 1, topic: "Botany" }
    ],
    government: [
        { question: "The system of government where power is shared is?", options: ["Unitary", "Federal", "Monarchy", "Confederal"], answer: 1, topic: "Federalism" },
        { question: "The highest law in a country is the?", options: ["Manifesto", "Decree", "Constitution", "By-law"], answer: 2, topic: "Constitution" },
        { question: "The right to vote is called?", options: ["Franchise", "Election", "Plebiscite", "Referendum"], answer: 0, topic: "Elections" },
        { question: "How many senators represent each state in Nigeria?", options: ["1", "2", "3", "4"], answer: 2, topic: "Legislature" },
        { question: "The head of a kingdom is a?", options: ["President", "Governor", "Monarch", "Prime Minister"], answer: 2, topic: "Monarchy" },
        { question: "Democracy is government of the people, by the ___", options: ["Rich", "Kings", "Military", "People"], answer: 3, topic: "Democracy" },
        { question: "Who was the first ceremonial president of Nigeria?", options: ["Nnamdi Azikiwe", "Tafawa Balewa", "Obasanjo", "Buhari"], answer: 0, topic: "History" },
        { question: "The organ that makes laws is the?", options: ["Executive", "Judiciary", "Legislature", "Police"], answer: 2, topic: "Organs of Govt" },
        { question: "The organ that interprets laws is the?", options: ["Executive", "Judiciary", "Legislature", "Army"], answer: 1, topic: "Organs of Govt" },
        { question: "A state with one central government is a ___ state.", options: ["Unitary", "Federal", "Confederal", "Military"], answer: 0, topic: "Unitary System" },
        { question: "The first capital of Nigeria was?", options: ["Abuja", "Lagos", "Calabar", "Kaduna"], answer: 2, topic: "History" },
        { question: "Which body conducts elections in Nigeria?", options: ["EFCC", "INEC", "NAPTIP", "NEMA"], answer: 1, topic: "Elections" },
        { question: "The rule of law means?", options: ["Police is supreme", "Law is supreme", "President is supreme", "Kings are supreme"], answer: 1, topic: "Concepts" },
        { question: "A two-house legislature is called?", options: ["Unicameral", "Bicameral", "Tricameral", "Dualist"], answer: 1, topic: "Legislature" },
        { question: "The ECOWAS headquarters is in?", options: ["Accra", "Abuja", "Lome", "Dakar"], answer: 1, topic: "International Orgs" },
        { question: "Who moved the motion for Nigerian independence in 1953?", options: ["Herbert Macaulay", "Anthony Enahoro", "Obafemi Awolowo", "Ahmadu Bello"], answer: 1, topic: "History" },
        { question: "Public corporations are funded by?", options: ["Private individuals", "Taxpayers", "Foreigners", "Churches"], answer: 1, topic: "Public Admin" },
        { question: "The tenure of the Nigerian President is ___ years.", options: ["2", "4", "5", "6"], answer: 1, topic: "Executive" },
        { question: "Communism was popularized by?", options: ["Adam Smith", "Karl Marx", "John Locke", "Plato"], answer: 1, topic: "Ideologies" },
        { question: "Which of these is a pressure group?", options: ["PDP", "APC", "ASUU", "LP"], answer: 2, topic: "Pressure Groups" },
        { question: "The headquarters of the UN is in?", options: ["London", "Paris", "New York", "Geneva"], answer: 2, topic: "International Orgs" },
        { question: "A cabinet system is also called ___ system.", options: ["Presidential", "Parliamentary", "Monarchical", "Autocratic"], answer: 1, topic: "Systems of Govt" },
        { question: "Separation of powers was proposed by?", options: ["Hobbes", "Montesquieu", "Marx", "Rousseau"], answer: 1, topic: "Concepts" },
        { question: "Nationalism is?", options: ["Love for family", "Love for country", "Love for money", "Love for war"], answer: 1, topic: "Nationalism" },
        { question: "The upper house in Nigeria is the?", options: ["House of Reps", "Senate", "Supreme Court", "State Assembly"], answer: 1, topic: "Legislature" },
        { question: "Delegated legislation is made by?", options: ["Judges", "Parliament", "Non-legislative bodies", "Citizens"], answer: 2, topic: "Legislature" },
        { question: "Universal Adult Suffrage means?", options: ["Only men vote", "Only rich vote", "All qualified adults vote", "Military votes"], answer: 2, topic: "Elections" },
        { question: "Gerrymandering is related to?", options: ["Courts", "Voting districts", "Budgeting", "Diplomacy"], answer: 1, topic: "Elections" },
        { question: "The first Nigerian military head of state was?", options: ["Gowon", "Aguiyi-Ironsi", "Murtala", "Babangida"], answer: 1, topic: "History" },
        { question: "Judicial review is a function of?", options: ["Police", "Courts", "President", "Senate"], answer: 1, topic: "Judiciary" },
        { question: "The African Union (AU) replaced the?", options: ["ECOWAS", "OAU", "UN", "NATO"], answer: 1, topic: "International Orgs" },
        { question: "Human rights are protected by the?", options: ["Constitution", "Manifesto", "Newspapers", "Trade unions"], answer: 0, topic: "Rights" },
        { question: "Fascism started in?", options: ["Germany", "Italy", "France", "Russia"], answer: 1, topic: "Ideologies" },
        { question: "A bill becomes law after the President's ___", options: ["Reading", "Assent", "Veto", "Debate"], answer: 1, topic: "Legislature" },
        { question: "Local governments are the ___ tier of govt.", options: ["1st", "2nd", "3rd", "4th"], answer: 2, topic: "Local Govt" },
        { question: "The Civil Service is headed by?", options: ["Minister", "Head of Service", "Governor", "Senator"], answer: 1, topic: "Civil Service" },
        { question: "Political parties aim to?", options: ["Make money", "Win elections", "Build roads", "Teach people"], answer: 1, topic: "Parties" },
        { question: "Anarchy is a state of?", options: ["Order", "Lawlessness", "Wealth", "Peace"], answer: 1, topic: "Ideologies" },
        { question: "Diplomacy is used in?", options: ["War", "Elections", "International relations", "Farming"], answer: 2, topic: "Concepts" },
        { question: "Citizenship by birth means?", options: ["Born in the country", "Living for 10 years", "Married to a citizen", "Honored by president"], answer: 0, topic: "Citizenship" }
    ],
    economics: [
        { question: "Economics is a study of how people deal with?", options: ["Scarcity", "Wealth", "Money", "Taxes"], answer: 0, topic: "Basics" },
        { question: "The scale of preference helps in making?", options: ["Money", "Choices", "Trade", "Loans"], answer: 1, topic: "Concepts" },
        { question: "Opportunity cost is also called?", options: ["Money cost", "Real cost", "Fixed cost", "Variable cost"], answer: 1, topic: "Concepts" },
        { question: "Demand curve usually slopes?", options: ["Upward", "Downward", "Horizontally", "Vertically"], answer: 1, topic: "Demand" },
        { question: "The reward for Labor is?", options: ["Profit", "Rent", "Interest", "Wages"], answer: 3, topic: "Production" },
        { question: "Microeconomics deals with?", options: ["National income", "Individual units", "Inflation", "Trade"], answer: 1, topic: "Scope" },
        { question: "The father of Modern Economics is?", options: ["Karl Marx", "Adam Smith", "John Keynes", "Alfred Marshall"], answer: 1, topic: "History" },
        { question: "Utility means?", options: ["Usefulness", "Satisfaction", "Need", "Price"], answer: 1, topic: "Utility" },
        { question: "Equilibrium is where demand ___ supply.", options: ["Exceeds", "Is less than", "Equals", "Doubles"], answer: 2, topic: "Market" },
        { question: "Money is a medium of?", options: ["Exchange", "Production", "Labor", "Capital"], answer: 0, topic: "Money" },
        { question: "Inflation means general ___ in prices.", options: ["Fall", "Rise", "Stability", "Fixing"], answer: 1, topic: "Inflation" },
        { question: "The central bank of Nigeria is?", options: ["First Bank", "Zenith", "CBN", "UBA"], answer: 2, topic: "Banking" },
        { question: "Gross Domestic Product (GDP) measures?", options: ["Total output", "Total debt", "Total population", "Total taxes"], answer: 0, topic: "National Income" },
        { question: "A budget with more revenue than spending is?", options: ["Deficit", "Surplus", "Balanced", "Fixed"], answer: 1, topic: "Budget" },
        { question: "The reward for Capital is?", options: ["Wages", "Rent", "Profit", "Interest"], answer: 3, topic: "Production" },
        { question: "Sole proprietorship is owned by?", options: ["Two people", "Government", "One person", "Shareholders"], answer: 2, topic: "Business Org" },
        { question: "Division of labor leads to?", options: ["Boredom", "Specialization", "Laziness", "Confusion"], answer: 1, topic: "Production" },
        { question: "Elasticity of demand measures response to?", options: ["Weather", "Price change", "Time", "Population"], answer: 1, topic: "Elasticity" },
        { question: "Which of these is a direct tax?", options: ["VAT", "Custom duty", "Income tax", "Excise duty"], answer: 2, topic: "Taxation" },
        { question: "Monopoly means ___ seller.", options: ["One", "Two", "Many", "No"], answer: 0, topic: "Market Structures" },
        { question: "International trade involves ___ countries.", options: ["Within one", "Between two or more", "No", "Cities"], answer: 1, topic: "Trade" },
        { question: "The law of diminishing returns applies to?", options: ["Demand", "Supply", "Production", "Utility"], answer: 2, topic: "Production" },
        { question: "Balance of trade is the difference between?", options: ["Income/Tax", "Export/Import", "Birth/Death", "Rich/Poor"], answer: 1, topic: "Trade" },
        { question: "Liquidity means ease of turning assets into?", options: ["Gold", "Cash", "Land", "Goods"], answer: 1, topic: "Money" },
        { question: "The main aim of a firm is?", options: ["Build schools", "Maximize profit", "Help poor", "Pay tax"], answer: 1, topic: "Firm" },
        { question: "A commodity used as money in the past is?", options: ["Credit card", "Cowry shells", "Cheques", "Paper notes"], answer: 1, topic: "Money" },
        { question: "Devaluation makes exports ___", options: ["Dearer", "Cheaper", "Stop", "Double"], answer: 1, topic: "Trade" },
        { question: "The labor force consists of people aged?", options: ["0-10", "15-64", "70-90", "Only men"], answer: 1, topic: "Population" },
        { question: "Deficit budget is used during?", options: ["Inflation", "Recession", "Boom", "War"], answer: 1, topic: "Budget" },
        { question: "Which of these is fixed capital?", options: ["Raw materials", "Cash", "Machinery", "Electricity"], answer: 2, topic: "Production" },
        { question: "Price floor is also called?", options: ["Minimum price", "Maximum price", "Market price", "Fixed price"], answer: 0, topic: "Market" },
        { question: "OPEC deals with?", options: ["Gold", "Oil", "Food", "Cocoa"], answer: 1, topic: "International Orgs" },
        { question: "A market with few large sellers is?", options: ["Monopoly", "Oligopoly", "Perfect competition", "Monopsomy"], answer: 1, topic: "Market Structures" },
        { question: "Substitute goods are used?", options: ["Together", "Instead of each other", "Never", "In winter"], answer: 1, topic: "Demand" },
        { question: "Nationalization means govt taking over ___", options: ["Schools", "Private firms", "Churches", "Homes"], answer: 1, topic: "Concepts" },
        { question: "The long run is a period where?", options: ["No factor is fixed", "All factors are fixed", "Demand is zero", "Time stops"], answer: 0, topic: "Production" },
        { question: "Total cost = Fixed cost + ___", options: ["Profit", "Variable cost", "Marginal cost", "Rent"], answer: 1, topic: "Production" },
        { question: "Human wants are?", options: ["Limited", "Unlimited", "Fixed", "Scarce"], answer: 1, topic: "Basics" },
        { question: "The World Bank headquarters is in?", options: ["London", "Washington DC", "Abuja", "Tokyo"], answer: 1, topic: "International Orgs" },
        { question: "Who defines Economics as 'science of scarcity'?", options: ["Adam Smith", "Lionel Robbins", "Alfred Marshall", "Karl Marx"], answer: 1, topic: "Basics" }
    ],
    commerce: [
        { question: "Commerce is the study of?", options: ["Farming", "Trade and aids to trade", "Politics", "Religion"], answer: 1, topic: "Basics" },
        { question: "Aids to trade include?", options: ["Farming", "Banking", "Fishing", "Mining"], answer: 1, topic: "Aids to Trade" },
        { question: "Wholesalers buy in?", options: ["Small quantities", "Singles", "Bulk", "Retail"], answer: 2, topic: "Trade" },
        { question: "Insurance covers?", options: ["Profit", "Risks", "Birthdays", "Sales"], answer: 1, topic: "Aids to Trade" },
        { question: "A bill of lading is used in ___ trade.", options: ["Home", "Retail", "Foreign", "Local"], answer: 2, topic: "Foreign Trade" },
        { question: "Advertising aims to?", options: ["Hide goods", "Increase awareness", "Reduce price", "Pay tax"], answer: 1, topic: "Aids to Trade" },
        { question: "A partner who only provides capital is a?", options: ["Active partner", "Sleeping partner", "Nominal partner", "General partner"], answer: 1, topic: "Business Org" },
        { question: "Branding helps to?", options: ["Hide quality", "Identify products", "Decrease sales", "Ignore customers"], answer: 1, topic: "Marketing" },
        { question: "The document that allows a company to start business is?", options: ["Prospectus", "Article of Assoc", "Certificate of Inc", "Trading cert"], answer: 3, topic: "Company" },
        { question: "E-commerce means buying and selling via?", options: ["Post office", "Physical shops", "Internet", "Television"], answer: 2, topic: "Modern Trade" },
        { question: "Warehousing helps in?", options: ["Storage", "Manufacturing", "Mining", "Farming"], answer: 0, topic: "Aids to Trade" },
        { question: "A person who buys for personal use is a?", options: ["Retailer", "Wholesaler", "Consumer", "Agent"], answer: 2, topic: "Trade" },
        { question: "Barter system involves exchange of?", options: ["Money for goods", "Goods for goods", "Cheques", "Cards"], answer: 1, topic: "Basics" },
        { question: "A public limited company must have '___' in its name.", options: ["Ltd", "Plc", "Inc", "Corp"], answer: 1, topic: "Company" },
        { question: "Communication is an aid to trade because it?", options: ["Builds roads", "Links buyers and sellers", "Stores goods", "Protects goods"], answer: 1, topic: "Aids to Trade" },
        { question: "A 'bull' in the stock exchange expects prices to?", options: ["Fall", "Stay same", "Rise", "Crash"], answer: 2, topic: "Stock Exchange" },
        { question: "Trade within a country is ___ trade.", options: ["External", "International", "Home", "Export"], answer: 2, topic: "Home Trade" },
        { question: "The reward for a shareholder is?", options: ["Interest", "Salary", "Dividend", "Wages"], answer: 2, topic: "Company" },
        { question: "An invoice is a document of?", options: ["Payment", "Indebtedness", "Arrival", "Shipment"], answer: 1, topic: "Documents" },
        { question: "Which of these is a function of money?", options: ["Store of value", "Cause inflation", "Encourage barter", "Hide wealth"], answer: 0, topic: "Money" },
        { question: "Chamber of Commerce is an association of?", options: ["Students", "Businessmen", "Teachers", "Farmers"], answer: 1, topic: "Associations" },
        { question: "The policy of 'Caveat Emptor' means?", options: ["Seller beware", "Buyer beware", "Govt beware", "No one beware"], answer: 1, topic: "Legal" },
        { question: "Which of these is an example of 'Aids to Trade'?", options: ["Banking", "Quarrying", "Weaving", "Hunting"], answer: 0, topic: "Aids to Trade" },
        { question: "Sole proprietorship is popular because it?", options: ["Has large capital", "Is easy to start", "Has limited liability", "Has many owners"], answer: 1, topic: "Business Org" },
        { question: "Transport creates ___ utility.", options: ["Time", "Place", "Form", "Ownership"], answer: 1, topic: "Aids to Trade" },
        { question: "A person who sells in small quantities is?", options: ["Agent", "Retailer", "Broker", "Wholesaler"], answer: 1, topic: "Trade" },
        { question: "The premium is paid in ___", options: ["Banking", "Insurance", "Advertising", "Shipping"], answer: 1, topic: "Aids to Trade" },
        { question: "A market for long term funds is?", options: ["Money market", "Capital market", "Black market", "Supermarket"], answer: 1, topic: "Finance" },
        { question: "Invisible trade refers to trade in?", options: ["Gold", "Services", "Cars", "Oil"], answer: 1, topic: "Foreign Trade" },
        { question: "An 'actuary' is found in?", options: ["Banking", "Insurance", "Customs", "Police"], answer: 1, topic: "Aids to Trade" },
        { question: "Tariffs are?", options: ["Gifts", "Taxes on imports", "Subsidies", "Loans"], answer: 1, topic: "Foreign Trade" },
        { question: "A 'bear' in the stock exchange expects prices to?", options: ["Fall", "Rise", "Double", "Triple"], answer: 0, topic: "Stock Exchange" },
        { question: "The bank that issues currency is?", options: ["Commercial bank", "Central bank", "Merchant bank", "Mortgage bank"], answer: 1, topic: "Banking" },
        { question: "Departmental stores sell ___", options: ["One line of goods", "Many lines of goods", "Only food", "Only drugs"], answer: 1, topic: "Retail" },
        { question: "Nationalization means?", options: ["Selling to public", "Govt ownership", "Private ownership", "Closing business"], answer: 1, topic: "Concepts" },
        { question: "The document showing rules of a company is?", options: ["Article of Association", "Memorandum of Assoc", "Prospectus", "Dividend"], answer: 0, topic: "Company" },
        { question: "The maximum number of partners in a general firm is?", options: ["2", "7", "20", "50"], answer: 2, topic: "Business Org" },
        { question: "Vending machines are used in?", options: ["Wholesale", "Automatic retailing", "Foreign trade", "Banking"], answer: 1, topic: "Retail" },
        { question: "Hire purchase allows payment in?", options: ["Bulk", "Advance", "Installments", "Gold"], answer: 2, topic: "Retail" },
        { question: "The primary aim of commerce is?", options: ["Production", "Distribution", "Consumption", "Mining"], answer: 1, topic: "Basics" }
    ],
    accounting: [
        { question: "Who is the father of double-entry bookkeeping?", options: ["Adam Smith", "Luca Pacioli", "Karl Marx", "Bill Gates"], answer: 1, topic: "History" },
        { question: "The Accounting Equation is?", options: ["Assets = Cap + Liab", "Cap = Assets + Liab", "Liab = Assets + Cap", "Assets = Cap - Liab"], answer: 0, topic: "Principles" },
        { question: "A debit entry usually signifies?", options: ["Decrease in asset", "Increase in asset", "Increase in liability", "Increase in revenue"], answer: 1, topic: "Double Entry" },
        { question: "Which book is used to record daily transactions?", options: ["Ledger", "Journal", "Trial Balance", "Balance Sheet"], answer: 1, topic: "Books of Entry" },
        { question: "Cash at hand is a ___ asset.", options: ["Fixed", "Current", "Fictitious", "Long term"], answer: 1, topic: "Classification" },
        { question: "A list of balances to check accuracy is?", options: ["Cash book", "Journal", "Trial Balance", "Trading account"], answer: 2, topic: "Trial Balance" },
        { question: "The process of transferring journal entries to ledger is?", options: ["Balancing", "Casting", "Posting", "Closing"], answer: 2, topic: "Double Entry" },
        { question: "Net Profit is calculated in ___ account.", options: ["Trading", "Profit & Loss", "Balance Sheet", "Cash book"], answer: 1, topic: "Final Accounts" },
        { question: "Bad debts are?", options: ["Good loans", "Irrecoverable debts", "Interest", "Sales"], answer: 1, topic: "Classification" },
        { question: "Depreciation is the ___ in value of fixed assets.", options: ["Increase", "Stability", "Reduction", "Doubling"], answer: 2, topic: "Depreciation" },
        { question: "A Petty Cash book is used for?", options: ["Large payments", "Small payments", "Bank loans", "Credit sales"], answer: 1, topic: "Cash Book" },
        { question: "Which of these is a liability?", options: ["Land", "Machinery", "Creditor", "Debtor"], answer: 2, topic: "Classification" },
        { question: "Drawings means owner taking ___ for personal use.", options: ["Loan", "Cash/Goods", "Office space", "Staff"], answer: 1, topic: "Principles" },
        { question: "The 'Golden Rule' for real accounts is?", options: ["Debit what goes out", "Debit what comes in", "Credit what comes in", "Debit the giver"], answer: 1, topic: "Double Entry" },
        { question: "A balance sheet shows the ___ position of a firm.", options: ["Management", "Political", "Financial", "Social"], answer: 2, topic: "Final Accounts" },
        { question: "Error of Omission means?", options: ["Wrong amount", "Wrong side", "Transaction not recorded", "Wrong account"], answer: 2, topic: "Errors" },
        { question: "Sales Journal records ___ sales.", options: ["Cash", "Credit", "Both", "None"], answer: 1, topic: "Books of Entry" },
        { question: "Which of these is a fixed asset?", options: ["Stock", "Debtor", "Motor Vehicle", "Cash"], answer: 2, topic: "Classification" },
        { question: "A Bank Reconciliation Statement is prepared by?", options: ["The Bank", "The Customer", "The Government", "Creditors"], answer: 1, topic: "Bank Recon" },
        { question: "Current Ratio formula is?", options: ["CA / CL", "CL / CA", "Total Assets / Liab", "Cash / Assets"], answer: 0, topic: "Ratios" },
        { question: "A person to whom the business owes money is a?", options: ["Debtor", "Creditor", "Investor", "Employee"], answer: 1, topic: "Classification" },
        { question: "The credit side of a Profit & Loss account shows?", options: ["Expenses", "Incomes", "Assets", "Liabilities"], answer: 1, topic: "Final Accounts" },
        { question: "What is the purpose of a Journal?", options: ["Check accuracy", "Show final profit", "Record chronologically", "Show financial status"], answer: 2, topic: "Books of Entry" },
        { question: "Double entry means?", options: ["Two people recording", "Two sides to a transaction", "Recording twice", "Deleting entries"], answer: 1, topic: "Double Entry" },
        { question: "Imprest system is related to?", options: ["Final accounts", "Petty cash book", "Bank statement", "Suspense account"], answer: 1, topic: "Cash Book" },
        { question: "Error of Principle means?", options: ["Math error", "Entry in wrong type of account", "Wrong person", "Double entry"], answer: 1, topic: "Errors" },
        { question: "Suspense account is used when?", options: ["Profit is high", "Trial balance doesn't agree", "Asset is sold", "Owner dies"], answer: 1, topic: "Errors" },
        { question: "Goodwill is an ___ asset.", options: ["Tangible", "Intangible", "Current", "Fictitious"], answer: 1, topic: "Classification" },
        { question: "Capital = Total Assets - ___", options: ["Current Assets", "Liabilities", "Profit", "Drawings"], answer: 1, topic: "Principles" },
        { question: "Carriage Inwards is added to?", options: ["Sales", "Purchases", "Expenses", "Capital"], answer: 1, topic: "Final Accounts" },
        { question: "Working Capital = Current Assets - ___", options: ["Fixed Assets", "Current Liabilities", "Long term loans", "Drawings"], answer: 1, topic: "Ratios" },
        { question: "Purchase Journal records ___ purchases.", options: ["Cash", "Credit", "Both", "Asset"], answer: 1, topic: "Books of Entry" },
        { question: "The excess of income over expenditure in non-profits is?", options: ["Profit", "Surplus", "Deficit", "Dividend"], answer: 1, topic: "Non-Profits" },
        { question: "Gross Profit = Sales - ___", options: ["Expenses", "Cost of Goods Sold", "Tax", "Net Profit"], answer: 1, topic: "Final Accounts" },
        { question: "Prepayments are ___ in the Balance Sheet.", options: ["Liabilities", "Assets", "Expenses", "Revenue"], answer: 1, topic: "Final Accounts" },
        { question: "Which of these is a nominal account?", options: ["Cash", "Land", "Rent", "Bank"], answer: 2, topic: "Double Entry" },
        { question: "A Credit Note is issued for?", options: ["Sales", "Returns Inwards", "Cash payment", "Loan"], answer: 1, topic: "Documents" },
        { question: "Accounting is the language of ___", options: ["Poetry", "Business", "Law", "Science"], answer: 1, topic: "Basics" },
        { question: "The matching concept means?", options: ["Assets = Liab", "Income matched with expenses", "Debit = Credit", "Stock = Sales"], answer: 1, topic: "Principles" },
        { question: "Accrued expenses are?", options: ["Paid in advance", "Owed but not paid", "Written off", "Hidden"], answer: 1, topic: "Final Accounts" }
    ],
    literature: [
        { question: "What is a 'Simile'?", options: ["Direct comparison", "Comparison using like or as", "Exaggeration", "Giving life to objects"], answer: 1, topic: "Figures of Speech" },
        { question: "A play is also known as?", options: ["Prose", "Poetry", "Drama", "Epic"], answer: 2, topic: "Genres" },
        { question: "Who wrote 'The Trials of Brother Jero'?", options: ["Chinua Achebe", "Wole Soyinka", "Cyprian Ekwensi", "Ken Saro-Wiwa"], answer: 1, topic: "Authors" },
        { question: "The main character in a story is the?", options: ["Antagonist", "Protagonist", "Villain", "Narrator"], answer: 1, topic: "Characters" },
        { question: "A poem of fourteen lines is a?", options: ["Sonnet", "Epic", "Elegy", "Ode"], answer: 0, topic: "Poetry" },
        { question: "The repetition of consonant sounds at the start of words is?", options: ["Onomatopoeia", "Alliteration", "Rhyme", "Metaphor"], answer: 1, topic: "Figures of Speech" },
        { question: "A poem written for the dead is an?", options: ["Ode", "Elegy", "Ballad", "Sonnet"], answer: 1, topic: "Poetry" },
        { question: "Exaggeration for effect is?", options: ["Irony", "Hyperbole", "Oxymoron", "Pun"], answer: 1, topic: "Figures of Speech" },
        { question: "The setting of a story refers to?", options: ["Characters", "Time and Place", "Plot", "Theme"], answer: 1, topic: "Elements" },
        { question: "What is a 'Metaphor'?", options: ["Comparison with 'like'", "Direct comparison", "Sound word", "Play on words"], answer: 1, topic: "Figures of Speech" },
        { question: "The opposing force to the hero is the?", options: ["Protagonist", "Antagonist", "Supporting actor", "Foil"], answer: 1, topic: "Characters" },
        { question: "Who wrote 'Things Fall Apart'?", options: ["Wole Soyinka", "Chinua Achebe", "Flora Nwapa", "Buchi Emecheta"], answer: 1, topic: "Authors" },
        { question: "A long narrative poem about heroes is an?", options: ["Epic", "Lyric", "Ode", "Ballad"], answer: 0, topic: "Poetry" },
        { question: "Words that sound like what they mean are?", options: ["Puns", "Onomatopoeia", "Irony", "Symbolism"], answer: 1, topic: "Figures of Speech" },
        { question: "The lesson of a story is the?", options: ["Theme", "Plot", "Moral", "Climax"], answer: 2, topic: "Elements" },
        { question: "A funny play is a?", options: ["Tragedy", "Comedy", "Melodrama", "Opera"], answer: 1, topic: "Drama" },
        { question: "A sad play ending in death is a?", options: ["Comedy", "Tragedy", "Satire", "Farcr"], answer: 1, topic: "Drama" },
        { question: "The sequence of events in a story is the?", options: ["Theme", "Setting", "Plot", "Conflict"], answer: 2, topic: "Elements" },
        { question: "Giving human qualities to non-humans is?", options: ["Metaphor", "Personification", "Simile", "Irony"], answer: 1, topic: "Figures of Speech" },
        { question: "A story where animals talk to teach a lesson is a?", options: ["Fable", "Myth", "Legend", "Novel"], answer: 0, topic: "Genres" },
        { question: "The voice telling the story in prose is the?", options: ["Speaker", "Narrator", "Persona", "Character"], answer: 1, topic: "Elements" },
        { question: "The highest point of tension in a story is the?", options: ["Conflict", "Climax", "Resolution", "Prologue"], answer: 1, topic: "Elements" },
        { question: "Two opposite words used together (e.g., Bitter-sweet) is?", options: ["Metonymy", "Oxymoron", "Synecdoche", "Irony"], answer: 1, topic: "Figures of Speech" },
        { question: "A short story written by a person about their own life is?", options: ["Biography", "Autobiography", "Novel", "Diary"], answer: 1, topic: "Genres" },
        { question: "What is a 'Pun'?", options: ["Direct comparison", "Play on words", "Exaggeration", "Symbol"], answer: 1, topic: "Figures of Speech" },
        { question: "The list of characters at the start of a play is?", options: ["Prologue", "Cast/Dramatis Personae", "Epilogue", "Script"], answer: 1, topic: "Drama" },
        { question: "When the audience knows more than the character, it is ___ irony.", options: ["Verbal", "Situational", "Dramatic", "Sarcastic"], answer: 2, topic: "Irony" },
        { question: "A long speech by a character alone on stage is a?", options: ["Dialogue", "Monologue", "Soliloquy", "Aside"], answer: 2, topic: "Drama" },
        { question: "Words spoken by a character to the audience only is an?", options: ["Aside", "Soliloquy", "Dialogue", "Prologue"], answer: 0, topic: "Drama" },
        { question: "A poem that tells a story and can be sung is a?", options: ["Lullaby", "Ballad", "Epic", "Ode"], answer: 1, topic: "Poetry" },
        { question: "The person telling a poem is the?", options: ["Narrator", "Persona", "Poet", "Speaker"], answer: 1, topic: "Poetry" },
        { question: "Irony that uses biting or harsh words to mock is?", options: ["Sarcasm", "Paradox", "Pun", "Satire"], answer: 0, topic: "Irony" },
        { question: "A literary work that mocks society to reform it is?", options: ["Tragedy", "Satire", "Fable", "Epic"], answer: 1, topic: "Genres" },
        { question: "Using a part to represent a whole (e.g., All hands on deck) is?", options: ["Metonymy", "Synecdoche", "Personification", "Simile"], answer: 1, topic: "Figures of Speech" },
        { question: "The use of objects to represent abstract ideas is?", options: ["Symbolism", "Paradox", "Irony", "Imagery"], answer: 0, topic: "Figures of Speech" },
        { question: "The 'turning point' in a tragedy where the hero falls is?", options: ["Climax", "Peripeteia", "Resolution", "Conflict"], answer: 1, topic: "Drama" },
        { question: "Which of these is a genre of literature?", options: ["Biology", "Drama", "History", "Physics"], answer: 1, topic: "Genres" },
        { question: "A stanza of four lines is a?", options: ["Couplet", "Quatrain", "Sestet", "Octave"], answer: 1, topic: "Poetry" },
        { question: "Words like 'clatter', 'bang', 'pop' are examples of?", options: ["Imagery", "Onomatopoeia", "Alliteration", "Rhyme"], answer: 1, topic: "Figures of Speech" },
        { question: "The mood or atmosphere of a literary work is the?", options: ["Theme", "Tone", "Plot", "Setting"], answer: 1, topic: "Elements" }
    ],
    crs: [
        { question: "How many days did it take God to create the world?", options: ["6", "7", "5", "10"], answer: 0, topic: "Creation" },
        { question: "Who was the first man created?", options: ["Cain", "Abel", "Adam", "Seth"], answer: 2, topic: "Creation" },
        { question: "Who built the Ark to save animals from the flood?", options: ["Moses", "Abraham", "Noah", "David"], answer: 2, topic: "Old Testament" },
        { question: "The first book of the Bible is?", options: ["Exodus", "Genesis", "Matthew", "Psalms"], answer: 1, topic: "Bible Structure" },
        { question: "Who received the Ten Commandments on Mt. Sinai?", options: ["Joshua", "Aaron", "Moses", "Samson"], answer: 2, topic: "Moses" },
        { question: "Where was Jesus born?", options: ["Jerusalem", "Nazareth", "Bethlehem", "Galilee"], answer: 2, topic: "Jesus' Life" },
        { question: "Who was the mother of Jesus?", options: ["Sarah", "Elizabeth", "Mary", "Martha"], answer: 2, topic: "Jesus' Life" },
        { question: "How many disciples did Jesus have?", options: ["10", "12", "7", "40"], answer: 1, topic: "Disciples" },
        { question: "Who betrayed Jesus to the authorities?", options: ["Peter", "John", "Judas Iscariot", "Thomas"], answer: 2, topic: "Passion" },
        { question: "Which disciple denied Jesus three times?", options: ["James", "Peter", "Andrew", "Judas"], answer: 1, topic: "Passion" },
        { question: "Who was the strongest man in the Bible?", options: ["Goliath", "David", "Samson", "Solomon"], answer: 2, topic: "Samson" },
        { question: "Who killed Goliath with a sling and a stone?", options: ["Saul", "Jonathan", "David", "Samuel"], answer: 2, topic: "David" },
        { question: "Which king was famous for his wisdom?", options: ["Rehoboam", "David", "Solomon", "Hezekiah"], answer: 2, topic: "Kings" },
        { question: "The shortest verse in the Bible is?", options: ["Jesus wept", "God is love", "Pray always", "Rejoice evermore"], answer: 0, topic: "Bible Facts" },
        { question: "How many books are in the New Testament?", options: ["39", "27", "66", "12"], answer: 1, topic: "Bible Structure" },
        { question: "The first miracle of Jesus was turning water into?", options: ["Blood", "Wine", "Milk", "Honey"], answer: 1, topic: "Miracles" },
        { question: "Who was swallowed by a great fish?", options: ["Jonah", "Job", "Elijah", "Elisha"], answer: 0, topic: "Prophets" },
        { question: "Who walked on water with Jesus for a moment?", options: ["John", "Paul", "Peter", "Matthew"], answer: 2, topic: "Miracles" },
        { question: "The last book of the Bible is?", options: ["Jude", "Revelation", "Malachi", "Hebrews"], answer: 1, topic: "Bible Structure" },
        { question: "Who led the Israelites out of Egypt?", options: ["Joshua", "Caleb", "Moses", "Joseph"], answer: 2, topic: "Exodus" },
        { question: "Who was thrown into the lions' den?", options: ["Shadrach", "Daniel", "Meshach", "Abednego"], answer: 1, topic: "Prophets" },
        { question: "The three Hebrew boys were thrown into a?", options: ["Pit", "River", "Fiery Furnace", "Jail"], answer: 2, topic: "Prophets" },
        { question: "Who was the coat of many colors given to?", options: ["Reuben", "Benjamin", "Joseph", "Isaac"], answer: 2, topic: "Joseph" },
        { question: "Jesus was baptized by ___ in the Jordan.", options: ["Peter", "James", "John the Baptist", "Paul"], answer: 2, topic: "Baptism" },
        { question: "Which city's walls fell after the Israelites marched?", options: ["Jericho", "Sodom", "Gomorrah", "Nineveh"], answer: 0, topic: "Joshua" },
        { question: "Who was the oldest man in the Bible?", options: ["Adam", "Methuselah", "Enoch", "Noah"], answer: 1, topic: "Genealogy" },
        { question: "The tax collector who climbed a tree to see Jesus was?", options: ["Matthew", "Zacchaeus", "Levi", "Paul"], answer: 1, topic: "Parables/Life" },
        { question: "Which miracle involved 5 loaves and 2 fish?", options: ["Feeding 5000", "Wedding at Cana", "Healing blind", "Raising Lazarus"], answer: 0, topic: "Miracles" },
        { question: "Who was the primary author of the Epistles?", options: ["Peter", "John", "Paul", "Luke"], answer: 2, topic: "Epistles" },
        { question: "Jesus taught in stories called?", options: ["Lyrics", "Poetry", "Parables", "Proverbs"], answer: 2, topic: "Teaching" },
        { question: "The name 'Emmanuel' means?", options: ["God is king", "God with us", "God is love", "Praise God"], answer: 1, topic: "Jesus' Life" },
        { question: "Who was the first king of Israel?", options: ["David", "Saul", "Solomon", "Samuel"], answer: 1, topic: "Kings" },
        { question: "Who was known as the 'weeping prophet'?", options: ["Isaiah", "Ezekiel", "Jeremiah", "Daniel"], answer: 2, topic: "Prophets" },
        { question: "On which day did Jesus rise from the dead?", options: ["Friday", "Saturday", "Sunday", "Monday"], answer: 2, topic: "Resurrection" },
        { question: "The Garden where Jesus prayed before arrest was?", options: ["Eden", "Gethsemane", "Sinai", "Carmel"], answer: 1, topic: "Passion" },
        { question: "Which commandment says 'Honor your father and mother'?", options: ["1st", "5th", "10th", "3rd"], answer: 1, topic: "Commandments" },
        { question: "Who was the wife of Isaac?", options: ["Sarah", "Rebekah", "Rachel", "Leah"], answer: 1, topic: "Patriarchs" },
        { question: "The provider of the Ten Commandments was ___", options: ["God", "Angel", "King", "Priest"], answer: 0, topic: "Moses" },
        { question: "Who was taken up to heaven in a chariot of fire?", options: ["Elijah", "Elisha", "Moses", "Enoc"], answer: 0, topic: "Prophets" },
        { question: "The first four books of the New Testament are the?", options: ["History", "Epistles", "Gospels", "Pentateuch"], answer: 2, topic: "Bible Structure" }
    ],
    biology: [
        { question: "Which blood vessel carries oxygenated blood away from the heart?", options: ["Vein", "Artery", "Capillary", "Venule"], answer: 1, topic: "Circulatory System" },
        { question: "What is the process of shedding the exoskeleton in insects?", options: ["Metamorphosis", "Ecdysis", "Hibernation", "Aestivation"], answer: 1, topic: "Insects" },
        { question: "The functional unit of the kidney is?", options: ["Nephron", "Neuron", "Alveoli", "Villi"], answer: 0, topic: "Excretion" },
        { question: "Which vitamin deficiency causes rickets?", options: ["Vit A", "Vit B", "Vit C", "Vit D"], answer: 3, topic: "Nutrition" },
        { question: "The site of protein synthesis is?", options: ["Mitochondria", "Ribosome", "Nucleus", "Golgi Body"], answer: 1, topic: "Cell Biology" },
        { question: "What is the study of the environment and organisms?", options: ["Genetics", "Ecology", "Taxonomy", "Physiology"], answer: 1, topic: "Ecology" },
        { question: "Which part of the flower receives pollen?", options: ["Anther", "Stigma", "Style", "Ovary"], answer: 1, topic: "Reproduction" },
        { question: "The 'survival of the fittest' theory was by?", options: ["Lamarck", "Darwin", "Mendel", "Linnaeus"], answer: 1, topic: "Evolution" },
        { question: "Which hormone is the 'fight or flight' hormone?", options: ["Insulin", "Adrenaline", "Thyroxine", "Estrogen"], answer: 1, topic: "Endocrine System" },
        { question: "A plant that grows on another plant for support is an?", options: ["Epiphyte", "Parasite", "Saprophyte", "Halophyte"], answer: 0, topic: "Plant Ecology" },
        { question: "The largest part of the human brain is the?", options: ["Cerebellum", "Medulla", "Cerebrum", "Hypothalamus"], answer: 2, topic: "Nervous System" },
        { question: "The production of energy without oxygen is ___ respiration.", options: ["Aerobic", "Anaerobic", "External", "Cellular"], answer: 1, topic: "Respiration" },
        { question: "Which organ stores bile?", options: ["Liver", "Gall bladder", "Pancreas", "Stomach"], answer: 1, topic: "Digestive System" },
        { question: "The cross between a tall and short pea plant is a?", options: ["Monohybrid cross", "Dihybrid cross", "Back cross", "Test cross"], answer: 0, topic: "Genetics" },
        { question: "What is the movement of gases in and out of the lungs?", options: ["Breathing", "Respiration", "Inhalation", "Diffusion"], answer: 0, topic: "Respiratory System" },
        { question: "The deficiency of Iodine causes?", options: ["Anemia", "Scurvy", "Goitre", "Beri-beri"], answer: 2, topic: "Nutrition" },
        { question: "Which organism causes malaria?", options: ["Mosquito", "Plasmodium", "Bacteria", "Virus"], answer: 1, topic: "Health" },
        { question: "The basic structure of a fungus is?", options: ["Root", "Hypha", "Leaf", "Cilium"], answer: 1, topic: "Classification" },
        { question: "A solution with a higher concentration than the cell is?", options: ["Hypotonic", "Hypertonic", "Isotonic", "Dilute"], answer: 1, topic: "Osmosis" },
        { question: "Which enzyme digests fats?", options: ["Amylase", "Pepsin", "Lipase", "Renin"], answer: 2, topic: "Digestive System" },
        { question: "The type of skeleton found in crabs is?", options: ["Endoskeleton", "Exoskeleton", "Hydrostatic", "None"], answer: 1, topic: "Support System" },
        { question: "Which part of the eye is sensitive to light?", options: ["Iris", "Pupil", "Retina", "Lens"], answer: 2, topic: "Senses" },
        { question: "The union of male and female gametes is?", options: ["Pollination", "Fertilization", "Ovulation", "Copulation"], answer: 1, topic: "Reproduction" },
        { question: "Plants that lose their leaves annually are?", options: ["Evergreen", "Deciduous", "Coniferous", "Annuals"], answer: 1, topic: "Plant Ecology" },
        { question: "Which of these is a social insect?", options: ["Housefly", "Termite", "Mosquito", "Butterfly"], answer: 1, topic: "Classification" },
        { question: "The 'building blocks' of proteins are?", options: ["Glucose", "Fatty acids", "Amino acids", "Glycerol"], answer: 2, topic: "Nutrition" },
        { question: "A group of individuals of the same species in an area is?", options: ["Community", "Population", "Ecosystem", "Biome"], answer: 1, topic: "Ecology" },
        { question: "Which organ filters blood and produces urine?", options: ["Heart", "Liver", "Kidney", "Lungs"], answer: 2, topic: "Excretion" },
        { question: "The main carbohydrate stored in animals is?", options: ["Starch", "Glycogen", "Cellulose", "Sucrose"], answer: 1, topic: "Nutrition" },
        { question: "What carries genetic information?", options: ["RNA", "DNA", "ATP", "NAD"], answer: 1, topic: "Genetics" },
        { question: "The study of fossils is?", options: ["Archaeology", "Paleontology", "Geology", "History"], answer: 1, topic: "Evolution" },
        { question: "Which mineral is needed for strong bones?", options: ["Iron", "Calcium", "Iodine", "Sodium"], answer: 1, topic: "Nutrition" },
        { question: "The heart is enclosed in a double membrane called?", options: ["Pleura", "Pericardium", "Peritoneum", "Meninges"], answer: 1, topic: "Circulatory System" },
        { question: "Which is the largest artery in the body?", options: ["Vena Cava", "Aorta", "Pulmonary Artery", "Carotid"], answer: 1, topic: "Circulatory System" },
        { question: "The process of getting rid of undigested food is?", options: ["Excretion", "Egestion", "Digestion", "Secretion"], answer: 1, topic: "Digestive System" },
        { question: "The male sex hormone is?", options: ["Estrogen", "Progesterone", "Testosterone", "Insulin"], answer: 2, topic: "Endocrine System" },
        { question: "Which organism is a primary producer?", options: ["Goat", "Lion", "Green Plant", "Fungi"], answer: 2, topic: "Ecology" },
        { question: "The type of joint in the shoulder is?", options: ["Hinge", "Pivot", "Ball and socket", "Gliding"], answer: 2, topic: "Support System" },
        { question: "What prevents the backflow of blood in the heart?", options: ["Veins", "Arteries", "Valves", "Capillaries"], answer: 2, topic: "Circulatory System" },
        { question: "The movement of a plant part towards light is?", options: ["Phototropism", "Geotropism", "Hydrotropism", "Thigmotropism"], answer: 0, topic: "Plant Physiology" }
    ],
    government: [
        { question: "How many local governments are in Nigeria?", options: ["774", "36", "109", "360"], answer: 0, topic: "Local Govt" },
        { question: "The first Nigerian President of the Senate was?", options: ["Nnamdi Azikiwe", "Ahmadu Bello", "Dennis Osadebay", "Tafawa Balewa"], answer: 0, topic: "History" },
        { question: "Which body approves the national budget?", options: ["Executive", "Judiciary", "Legislature", "Central Bank"], answer: 2, topic: "Legislature" },
        { question: "The 1979 constitution introduced the ___ system.", options: ["Parliamentary", "Presidential", "Military", "Monarchical"], answer: 1, topic: "Constitution" },
        { question: "The term of office for a Local Govt Chairman in Nigeria is usually?", options: ["2 years", "3 years", "4 years", "5 years"], answer: 1, topic: "Local Govt" },
        { question: "Which is the 'Fourth Estate of the Realm'?", options: ["The Army", "The Police", "The Press", "The Clergy"], answer: 2, topic: "Concepts" },
        { question: "Nigeria became a Republic in?", options: ["1960", "1963", "1966", "1970"], answer: 1, topic: "History" },
        { question: "A primary election is used to?", options: ["Elect President", "Select party candidates", "Appoint judges", "Choose a King"], answer: 1, topic: "Elections" },
        { question: "The system of 'checks and balances' prevents?", options: ["Tax evasion", "Dictatorship", "Elections", "Trade"], answer: 1, topic: "Concepts" },
        { question: "Who is the 'Father of Nigerian Nationalism'?", options: ["Herbert Macaulay", "Nnamdi Azikiwe", "Obafemi Awolowo", "Ahmadu Bello"], answer: 0, topic: "History" },
        { question: "The highest court in Nigeria is the?", options: ["High Court", "Court of Appeal", "Supreme Court", "Sharia Court"], answer: 2, topic: "Judiciary" },
        { question: "Fundamental Human Rights are found in?", options: ["Newspapers", "Textbooks", "The Constitution", "Religious books"], answer: 2, topic: "Rights" },
        { question: "The process of taking over a colony is?", options: ["Nationalization", "Colonization", "Immigration", "Diplomacy"], answer: 1, topic: "Concepts" },
        { question: "Public opinion is the view of ___", options: ["The King", "The Majority", "The Military", "The Rich"], answer: 1, topic: "Public Opinion" },
        { question: "The head of the Judiciary is the?", options: ["President", "Senate President", "Chief Justice", "Speaker"], answer: 2, topic: "Judiciary" },
        { question: "Rigging is an example of electoral ___", options: ["Malpractice", "Success", "Strategy", "Reform"], answer: 0, topic: "Elections" },
        { question: "The Lyttleton Constitution of 1954 made Nigeria a?", options: ["Unitary State", "Federation", "Kingdom", "Colony"], answer: 1, topic: "Constitution" },
        { question: "Which of these is a civil right?", options: ["Right to steal", "Right to life", "Right to kill", "Right to cheat"], answer: 1, topic: "Rights" },
        { question: "The Commonwealth is an association of?", options: ["African states", "Former British colonies", "Oil rich states", "European states"], answer: 1, topic: "International Orgs" },
        { question: "Impeachment is the removal of?", options: ["Judges", "The President/Governor", "Students", "Civil servants"], answer: 1, topic: "Executive" },
        { question: "Bureaucracy is associated with?", options: ["The Army", "Civil Service", "Churches", "Farms"], answer: 1, topic: "Civil Service" },
        { question: "A government by the few rich is an?", options: ["Aristocracy", "Oligarchy", "Democracy", "Autocracy"], answer: 1, topic: "Systems of Govt" },
        { question: "The first Nigerian military coup was in?", options: ["1960", "1966", "1975", "1983"], answer: 1, topic: "History" },
        { question: "Electoral commission in Nigeria is known as?", options: ["INEC", "NAPTIP", "EFCC", "NYSC"], answer: 0, topic: "Elections" },
        { question: "An election between two regular elections is a?", options: ["General election", "Bye-election", "Primary", "Referendum"], answer: 1, topic: "Elections" },
        { question: "The headquarters of the OAU (now AU) is in?", options: ["Lagos", "Cairo", "Addis Ababa", "Nairobi"], answer: 2, topic: "International Orgs" },
        { question: "Which ideology advocates for classless society?", options: ["Capitalism", "Socialism", "Communism", "Fascism"], answer: 2, topic: "Ideologies" },
        { question: "Judges are appointed by the President on recommendation of?", options: ["Senate", "National Judicial Council", "Police", "NBA"], answer: 1, topic: "Judiciary" },
        { question: "A secular state means?", options: ["State with many kings", "State with no official religion", "Religious state", "Military state"], answer: 1, topic: "Concepts" },
        { question: "The head of the Commonwealth is?", options: ["British Prime Minister", "The British Monarch", "UN Secretary", "US President"], answer: 1, topic: "International Orgs" },
        { question: "How many members are in the House of Representatives?", options: ["109", "360", "469", "774"], answer: 1, topic: "Legislature" },
        { question: "Pressure groups differ from parties because they?", options: ["Don't seek power", "Seek power", "Have many members", "Have money"], answer: 0, topic: "Pressure Groups" },
        { question: "The 'veto' power in UN belongs to ___ permanent members.", options: ["3", "5", "10", "15"], answer: 1, topic: "International Orgs" },
        { question: "Naturalization is a way of getting?", options: ["Money", "Citizenship", "Visa", "Passport"], answer: 1, topic: "Citizenship" },
        { question: "The Macpherson Constitution was in?", options: ["1922", "1946", "1951", "1960"], answer: 2, topic: "Constitution" },
        { question: "Who chairs the Federal Executive Council?", options: ["The President", "Vice President", "SGF", "Minister"], answer: 0, topic: "Executive" },
        { question: "A vote of 'No Confidence' happens in ___ system.", options: ["Presidential", "Parliamentary", "Confederal", "Monarchical"], answer: 1, topic: "Systems of Govt" },
        { question: "The Civil Service is characterized by?", options: ["Partiality", "Anonymity", "Profit", "Corruption"], answer: 1, topic: "Civil Service" },
        { question: "Red-tapism means?", options: ["Efficient service", "Excessive delay", "Coloring tapes", "Building roads"], answer: 1, topic: "Civil Service" },
        { question: "Which body manages the UN between sessions?", options: ["General Assembly", "Secretariat", "Security Council", "UNESCO"], answer: 1, topic: "International Orgs" }
    ],
    economics: [
        { question: "Opportunity cost is also called?", options: ["Money cost", "Alternative cost", "Fixed cost", "Variable cost"], answer: 1, topic: "Concepts" },
        { question: "Which market has many buyers and many sellers with identical products?", options: ["Monopoly", "Perfect Competition", "Oligopoly", "Duopoly"], answer: 1, topic: "Market Structures" },
        { question: "The main source of government revenue in Nigeria is?", options: ["Farming", "Crude Oil", "Gold", "Tourism"], answer: 1, topic: "Taxation/Revenue" },
        { question: "A decline in the value of a currency is?", options: ["Appreciation", "Depreciation", "Devaluation", "Inflation"], answer: 1, topic: "Money/Trade" },
        { question: "Production is complete when goods reach the?", options: ["Wholesaler", "Retailer", "Consumer", "Factory"], answer: 2, topic: "Production" },
        { question: "The demand for labor is a ___ demand.", options: ["Joint", "Derived", "Composite", "Direct"], answer: 1, topic: "Demand" },
        { question: "What is the formula for Total Revenue?", options: ["Price + Quantity", "Price x Quantity", "Price / Quantity", "Profit - Cost"], answer: 1, topic: "Firm" },
        { question: "Which of these is a variable cost?", options: ["Rent", "Interest on loan", "Raw materials", "Insurance"], answer: 2, topic: "Production" },
        { question: "Inflation caused by excess demand is ___ inflation.", options: ["Cost-push", "Demand-pull", "Hyper", "Moderate"], answer: 1, topic: "Inflation" },
        { question: "A market with only one buyer is a?", options: ["Monopoly", "Monopsony", "Oligopoly", "Perfect market"], answer: 1, topic: "Market Structures" },
        { question: "The Population Census is the count of people every ___ years.", options: ["2", "5", "10", "20"], answer: 2, topic: "Population" },
        { question: "Malthusian theory is about?", options: ["Trade", "Population", "Production", "Money"], answer: 1, topic: "Population" },
        { question: "Which of these is a commercial bank?", options: ["CBN", "Zenith Bank", "Mortgage bank", "Merchant bank"], answer: 1, topic: "Banking" },
        { question: "Economics is a ___ science.", options: ["Physical", "Social", "Natural", "Pure"], answer: 1, topic: "Basics" },
        { question: "Utility is maximum when Marginal Utility is?", options: ["High", "Zero", "Negative", "One"], answer: 1, topic: "Utility" },
        { question: "A graph showing the combination of two goods a country can produce is?", options: ["Demand curve", "Supply curve", "Production Possibility Curve", "Lorenz curve"], answer: 2, topic: "Concepts" },
        { question: "Normal goods have a ___ relationship between income and demand.", options: ["Negative", "Inverse", "Positive", "No"], answer: 2, topic: "Demand" },
        { question: "If demand is greater than supply, there is a?", options: ["Surplus", "Equilibrium", "Shortage", "Glut"], answer: 2, topic: "Market" },
        { question: "The 'invisible hand' was a term by?", options: ["Karl Marx", "Adam Smith", "Keynes", "Robbins"], answer: 1, topic: "Basics" },
        { question: "Which level of production is farming?", options: ["Primary", "Secondary", "Tertiary", "Quaternary"], answer: 0, topic: "Production" },
        { question: "What is the reward for land?", options: ["Wages", "Interest", "Rent", "Profit"], answer: 2, topic: "Production" },
        { question: "A firm's profit is maximized when?", options: ["MR = MC", "TR = TC", "AC = AR", "Price is high"], answer: 0, topic: "Firm" },
        { question: "National income divided by population is?", options: ["Total income", "Disposable income", "Per capita income", "Real income"], answer: 2, topic: "National Income" },
        { question: "Which of these is a function of money?", options: ["Cause inflation", "Measure of value", "Hide wealth", "Create debt"], answer: 1, topic: "Money" },
        { question: "The study of the economy as a whole is?", options: ["Microeconomics", "Macroeconomics", "Positive economics", "Applied economics"], answer: 1, topic: "Scope" },
        { question: "A budget deficit means govt spends ___ than it earns.", options: ["Less", "More", "Same", "Twice"], answer: 1, topic: "Public Finance" },
        { question: "Direct taxes are levied on?", options: ["Goods", "Income", "Imports", "Services"], answer: 1, topic: "Taxation" },
        { question: "Devaluation of currency makes imports?", options: ["Cheaper", "Dearer", "Better", "Free"], answer: 1, topic: "Trade" },
        { question: "The law of supply states that as price rises, supply?", options: ["Falls", "Rises", "Stays same", "Fluctuates"], answer: 1, topic: "Supply" },
        { question: "Goods that are used together are?", options: ["Substitutes", "Complements", "Luxuries", "Giffen goods"], answer: 1, topic: "Demand" },
        { question: "A price ceiling is a ___ price.", options: ["Minimum", "Maximum", "Market", "Standard"], answer: 1, topic: "Market" },
        { question: "Economics is the science which studies human behavior as a relationship between ends and ___", options: ["Wants", "Means", "Scarcity", "Money"], answer: 1, topic: "Basics" },
        { question: "The main objective of a socialist economy is?", options: ["Profit", "Welfare", "War", "Taxes"], answer: 1, topic: "Economic Systems" },
        { question: "Human wants are unlimited while resources are ___", options: ["Scarce", "Abundant", "Free", "Useless"], answer: 0, topic: "Basics" },
        { question: "Which of these is an aid to trade?", options: ["Banking", "Quarrying", "Fishing", "Mining"], answer: 0, topic: "Commerce" },
        { question: "A stock of goods held for sale is?", options: ["Capital", "Inventory", "Land", "Labor"], answer: 1, topic: "Firm" },
        { question: "Gross National Product (GNP) includes?", options: ["Only local output", "Local + Net income from abroad", "Only debt", "Only taxes"], answer: 1, topic: "National Income" },
        { question: "The central problem of economics is?", options: ["Money", "Scarcity", "Banking", "Taxation"], answer: 1, topic: "Basics" },
        { question: "Labor is a ___ factor of production.", options: ["Passive", "Active", "Fixed", "External"], answer: 1, topic: "Production" },
        { question: "Which cost does not change with output?", options: ["Variable", "Fixed", "Marginal", "Average"], answer: 1, topic: "Production" }
    ]
};
